--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA "ALG0"!

CREATE TABLE "ALG0"."DTT_AWAHR" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_AWAHR" VARGRAPHIC(6) NOT NULL, 
		"TARGET_AWAHR" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_DEAR3" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_DEAR3" VARGRAPHIC(2) NOT NULL, 
		"TARGET_DEAR3" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_DTAMS" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_DTAMS" VARGRAPHIC(2) NOT NULL, 
		"TARGET_DTAMS" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_DUEFL_BKPF" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_DUEFL_BKPF" VARGRAPHIC(2) NOT NULL, 
		"TARGET_DUEFL_BKPF" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_J_1BINDUS1" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_J_1BINDUS1" VARGRAPHIC(4) NOT NULL, 
		"TARGET_J_1BINDUS1" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_KZTLF" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KZTLF" VARGRAPHIC(2) NOT NULL, 
		"TARGET_KZTLF" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_PRATK" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_PRATK" VARGRAPHIC(2) NOT NULL, 
		"TARGET_PRATK" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_QKZ" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_QKZ" VARGRAPHIC(2) NOT NULL, 
		"TARGET_QKZ" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_STKZA" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_STKZA" VARGRAPHIC(2) NOT NULL, 
		"TARGET_STKZA" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_STKZN" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_STKZN" VARGRAPHIC(2) NOT NULL, 
		"TARGET_STKZN" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_XFELD" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_XFELD" VARGRAPHIC(2) NOT NULL, 
		"TARGET_XFELD" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT_ZINRT" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_ZINRT" VARGRAPHIC(4) NOT NULL, 
		"TARGET_ZINRT" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT__BEV1_EMGFORTS" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE__BEV1_EMGFORTS" VARGRAPHIC(2) NOT NULL, 
		"TARGET__BEV1_EMGFORTS" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT__BEV1_EMGPFAND" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE__BEV1_EMGPFAND" VARGRAPHIC(2) NOT NULL, 
		"TARGET__BEV1_EMGPFAND" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT__VSO_M_LOAD_PREF" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE__VSO_M_LOAD_PREF" VARGRAPHIC(2) NOT NULL, 
		"TARGET__VSO_M_LOAD_PREF" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT__VSO_M_SIDE_PREF" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE__VSO_M_SIDE_PREF" VARGRAPHIC(2) NOT NULL, 
		"TARGET__VSO_M_SIDE_PREF" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."DTT__VSO_M_XFIELD" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE__VSO_M_XFIELD" VARGRAPHIC(2) NOT NULL, 
		"TARGET__VSO_M_XFIELD" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."KNA1" (
		"MANDT" VARGRAPHIC(6), 
		"KUNNR" VARGRAPHIC(20), 
		"LAND1" VARGRAPHIC(6), 
		"NAME1" VARGRAPHIC(70), 
		"NAME2" VARGRAPHIC(70), 
		"ORT01" VARGRAPHIC(70), 
		"PSTLZ" VARGRAPHIC(20), 
		"REGIO" VARGRAPHIC(6), 
		"SORTL" VARGRAPHIC(20), 
		"STRAS" VARGRAPHIC(70), 
		"TELF1" VARGRAPHIC(32), 
		"TELFX" VARGRAPHIC(62), 
		"XCPDK" VARGRAPHIC(2), 
		"ADRNR" VARGRAPHIC(20), 
		"MCOD1" VARGRAPHIC(50), 
		"MCOD2" VARGRAPHIC(50), 
		"MCOD3" VARGRAPHIC(50), 
		"ANRED" VARGRAPHIC(30), 
		"AUFSD" VARGRAPHIC(4), 
		"BAHNE" VARGRAPHIC(50), 
		"BAHNS" VARGRAPHIC(50), 
		"BBBNR" VARGRAPHIC(14), 
		"BBSNR" VARGRAPHIC(10), 
		"BEGRU" VARGRAPHIC(8), 
		"BRSCH" VARGRAPHIC(8), 
		"BUBKZ" VARGRAPHIC(2), 
		"DATLT" VARGRAPHIC(28), 
		"ERDAT" VARGRAPHIC(16), 
		"ERNAM" VARGRAPHIC(24), 
		"EXABL" VARGRAPHIC(2), 
		"FAKSD" VARGRAPHIC(4), 
		"FISKN" VARGRAPHIC(20), 
		"KNAZK" VARGRAPHIC(4), 
		"KNRZA" VARGRAPHIC(20), 
		"KONZS" VARGRAPHIC(20), 
		"KTOKD" VARGRAPHIC(8), 
		"KUKLA" VARGRAPHIC(4), 
		"LIFNR" VARGRAPHIC(20), 
		"LIFSD" VARGRAPHIC(4), 
		"LOCCO" VARGRAPHIC(20), 
		"LOEVM" VARGRAPHIC(2), 
		"NAME3" VARGRAPHIC(70), 
		"NAME4" VARGRAPHIC(70), 
		"NIELS" VARGRAPHIC(4), 
		"ORT02" VARGRAPHIC(70), 
		"PFACH" VARGRAPHIC(20), 
		"PSTL2" VARGRAPHIC(20), 
		"COUNC" VARGRAPHIC(6), 
		"CITYC" VARGRAPHIC(8), 
		"RPMKR" VARGRAPHIC(10), 
		"SPERR" VARGRAPHIC(2), 
		"SPRAS" VARGRAPHIC(2), 
		"STCD1" VARGRAPHIC(32), 
		"STCD2" VARGRAPHIC(22), 
		"STKZA" VARGRAPHIC(2), 
		"STKZU" VARGRAPHIC(2), 
		"TELBX" VARGRAPHIC(30), 
		"TELF2" VARGRAPHIC(32), 
		"TELTX" VARGRAPHIC(60), 
		"TELX1" VARGRAPHIC(60), 
		"LZONE" VARGRAPHIC(20), 
		"XZEMP" VARGRAPHIC(2), 
		"VBUND" VARGRAPHIC(12), 
		"STCEG" VARGRAPHIC(40), 
		"DEAR1" VARGRAPHIC(2), 
		"DEAR2" VARGRAPHIC(2), 
		"DEAR3" VARGRAPHIC(2), 
		"DEAR4" VARGRAPHIC(2), 
		"DEAR5" VARGRAPHIC(2), 
		"GFORM" VARGRAPHIC(4), 
		"BRAN1" VARGRAPHIC(20), 
		"BRAN2" VARGRAPHIC(20), 
		"BRAN3" VARGRAPHIC(20), 
		"BRAN4" VARGRAPHIC(20), 
		"BRAN5" VARGRAPHIC(20), 
		"EKONT" VARGRAPHIC(20), 
		"UMSAT" VARGRAPHIC(20), 
		"UMJAH" VARGRAPHIC(8), 
		"UWAER" VARGRAPHIC(10), 
		"JMZAH" VARGRAPHIC(12), 
		"JMJAH" VARGRAPHIC(8), 
		"KATR1" VARGRAPHIC(4), 
		"KATR2" VARGRAPHIC(4), 
		"KATR3" VARGRAPHIC(4), 
		"KATR4" VARGRAPHIC(4), 
		"KATR5" VARGRAPHIC(4), 
		"KATR6" VARGRAPHIC(6), 
		"KATR7" VARGRAPHIC(6), 
		"KATR8" VARGRAPHIC(6), 
		"KATR9" VARGRAPHIC(6), 
		"KATR10" VARGRAPHIC(6), 
		"STKZN" VARGRAPHIC(2), 
		"UMSA1" VARGRAPHIC(34), 
		"TXJCD" VARGRAPHIC(30), 
		"PERIV" VARGRAPHIC(4), 
		"ABRVW" VARGRAPHIC(6), 
		"INSPBYDEBI" VARGRAPHIC(2), 
		"INSPATDEBI" VARGRAPHIC(2), 
		"KTOCD" VARGRAPHIC(8), 
		"PFORT" VARGRAPHIC(70), 
		"WERKS" VARGRAPHIC(8), 
		"DTAMS" VARGRAPHIC(2), 
		"DTAWS" VARGRAPHIC(4), 
		"DUEFL" VARGRAPHIC(2), 
		"HZUOR" VARGRAPHIC(4), 
		"SPERZ" VARGRAPHIC(2), 
		"ETIKG" VARGRAPHIC(20), 
		"CIVVE" VARGRAPHIC(2), 
		"MILVE" VARGRAPHIC(2), 
		"KDKG1" VARGRAPHIC(4), 
		"KDKG2" VARGRAPHIC(4), 
		"KDKG3" VARGRAPHIC(4), 
		"KDKG4" VARGRAPHIC(4), 
		"KDKG5" VARGRAPHIC(4), 
		"XKNZA" VARGRAPHIC(2), 
		"FITYP" VARGRAPHIC(4), 
		"STCDT" VARGRAPHIC(4), 
		"STCD3" VARGRAPHIC(36), 
		"STCD4" VARGRAPHIC(36), 
		"XICMS" VARGRAPHIC(2), 
		"XXIPI" VARGRAPHIC(2), 
		"XSUBT" VARGRAPHIC(6), 
		"CFOPC" VARGRAPHIC(4), 
		"TXLW1" VARGRAPHIC(6), 
		"TXLW2" VARGRAPHIC(6), 
		"CCC01" VARGRAPHIC(2), 
		"CCC02" VARGRAPHIC(2), 
		"CCC03" VARGRAPHIC(2), 
		"CCC04" VARGRAPHIC(2), 
		"CASSD" VARGRAPHIC(4), 
		"KNURL" VARGRAPHIC(264), 
		"J_1KFREPRE" VARGRAPHIC(20), 
		"J_1KFTBUS" VARGRAPHIC(60), 
		"J_1KFTIND" VARGRAPHIC(60), 
		"CONFS" VARGRAPHIC(2), 
		"UPDAT" VARGRAPHIC(16), 
		"UPTIM" VARGRAPHIC(12), 
		"NODEL" VARGRAPHIC(2), 
		"DEAR6" VARGRAPHIC(2), 
		"AVSO_R_PALHGT" VARGRAPHIC(30), 
		"AVSO_R_PAL_UL" VARGRAPHIC(6), 
		"AVSO_R_PK_MAT" VARGRAPHIC(2), 
		"AVSO_R_MATPAL" VARGRAPHIC(36), 
		"AVSO_R_I_NO_LYR" VARGRAPHIC(4), 
		"AVSO_R_ONE_MAT" VARGRAPHIC(2), 
		"AVSO_R_ONE_SORT" VARGRAPHIC(2), 
		"AVSO_R_ULD_SIDE" VARGRAPHIC(2), 
		"AVSO_R_LOAD_PREF" VARGRAPHIC(2), 
		"AVSO_R_DPOINT" VARGRAPHIC(20), 
		"ALC" VARGRAPHIC(16), 
		"PMT_OFFICE" VARGRAPHIC(10), 
		"FEE_SCHEDULE" VARGRAPHIC(8), 
		"DUNS" VARGRAPHIC(18), 
		"DUNS4" VARGRAPHIC(8), 
		"PSOFG" VARGRAPHIC(20), 
		"PSOIS" VARGRAPHIC(40), 
		"PSON1" VARGRAPHIC(70), 
		"PSON2" VARGRAPHIC(70), 
		"PSON3" VARGRAPHIC(70), 
		"PSOVN" VARGRAPHIC(70), 
		"PSOTL" VARGRAPHIC(40), 
		"PSOHS" VARGRAPHIC(12), 
		"PSOST" VARGRAPHIC(56), 
		"PSOO1" VARGRAPHIC(100), 
		"PSOO2" VARGRAPHIC(100), 
		"PSOO3" VARGRAPHIC(100), 
		"PSOO4" VARGRAPHIC(100), 
		"PSOO5" VARGRAPHIC(100), 
		"CW_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"CW_LEGACY_UK" VARGRAPHIC(120) NOT NULL, 
		"CW_LOB" VARGRAPHIC(10) NOT NULL, 
		"CW_RLOUT" VARGRAPHIC(30) NOT NULL, 
		"CW_CATEGORY" VARGRAPHIC(30) NOT NULL, 
		"CW_VERSION" INTEGER NOT NULL, 
		"CW_LOAD_ID" INTEGER NOT NULL, 
		"PK_KNA1" VARGRAPHIC(250) NOT NULL, 
		"FK_KNA1_FISKN" VARGRAPHIC(250), 
		"FK_KNA1_KNRZA" VARGRAPHIC(250)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."KNB1" (
		"MANDT" VARGRAPHIC(6), 
		"KUNNR" VARGRAPHIC(20), 
		"BUKRS" VARGRAPHIC(8), 
		"PERNR" VARGRAPHIC(16), 
		"ERDAT" VARGRAPHIC(16), 
		"ERNAM" VARGRAPHIC(24), 
		"SPERR" VARGRAPHIC(2), 
		"LOEVM" VARGRAPHIC(2), 
		"ZUAWA" VARGRAPHIC(6), 
		"BUSAB" VARGRAPHIC(4), 
		"AKONT" VARGRAPHIC(20), 
		"BEGRU" VARGRAPHIC(8), 
		"KNRZE" VARGRAPHIC(20), 
		"KNRZB" VARGRAPHIC(20), 
		"ZAMIM" VARGRAPHIC(2), 
		"ZAMIV" VARGRAPHIC(2), 
		"ZAMIR" VARGRAPHIC(2), 
		"ZAMIB" VARGRAPHIC(2), 
		"ZAMIO" VARGRAPHIC(2), 
		"ZWELS" VARGRAPHIC(20), 
		"XVERR" VARGRAPHIC(2), 
		"ZAHLS" VARGRAPHIC(2), 
		"ZTERM" VARGRAPHIC(8), 
		"WAKON" VARGRAPHIC(8), 
		"VZSKZ" VARGRAPHIC(4), 
		"ZINDT" VARGRAPHIC(16), 
		"ZINRT" VARGRAPHIC(4), 
		"EIKTO" VARGRAPHIC(24), 
		"ZSABE" VARGRAPHIC(30), 
		"KVERM" VARGRAPHIC(60), 
		"FDGRV" VARGRAPHIC(20), 
		"VRBKZ" VARGRAPHIC(4), 
		"VLIBB" VARGRAPHIC(30), 
		"VRSZL" VARGRAPHIC(10), 
		"VRSPR" VARGRAPHIC(10), 
		"VRSNR" VARGRAPHIC(20), 
		"VERDT" VARGRAPHIC(16), 
		"PERKZ" VARGRAPHIC(2), 
		"XDEZV" VARGRAPHIC(2), 
		"XAUSZ" VARGRAPHIC(2), 
		"WEBTR" VARGRAPHIC(30), 
		"REMIT" VARGRAPHIC(20), 
		"DATLZ" VARGRAPHIC(16), 
		"XZVER" VARGRAPHIC(2), 
		"TOGRU" VARGRAPHIC(8), 
		"KULTG" VARGRAPHIC(10), 
		"HBKID" VARGRAPHIC(10), 
		"XPORE" VARGRAPHIC(2), 
		"BLNKZ" VARGRAPHIC(4), 
		"ALTKN" VARGRAPHIC(20), 
		"ZGRUP" VARGRAPHIC(4), 
		"URLID" VARGRAPHIC(8), 
		"MGRUP" VARGRAPHIC(4), 
		"LOCKB" VARGRAPHIC(14), 
		"UZAWE" VARGRAPHIC(4), 
		"EKVBD" VARGRAPHIC(20), 
		"SREGL" VARGRAPHIC(6), 
		"XEDIP" VARGRAPHIC(2), 
		"FRGRP" VARGRAPHIC(8), 
		"VRSDG" VARGRAPHIC(6), 
		"TLFXS" VARGRAPHIC(62), 
		"INTAD" VARGRAPHIC(260), 
		"XKNZB" VARGRAPHIC(2), 
		"GUZTE" VARGRAPHIC(8), 
		"GRICD" VARGRAPHIC(4), 
		"GRIDT" VARGRAPHIC(4), 
		"WBRSL" VARGRAPHIC(4), 
		"CONFS" VARGRAPHIC(2), 
		"UPDAT" VARGRAPHIC(16), 
		"UPTIM" VARGRAPHIC(12), 
		"NODEL" VARGRAPHIC(2), 
		"TLFNS" VARGRAPHIC(60), 
		"CESSION_KZ" VARGRAPHIC(4), 
		"GMVKZD" VARGRAPHIC(2), 
		"CW_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"CW_LEGACY_UK" VARGRAPHIC(120) NOT NULL, 
		"CW_LOB" VARGRAPHIC(10) NOT NULL, 
		"CW_RLOUT" VARGRAPHIC(30) NOT NULL, 
		"CW_CATEGORY" VARGRAPHIC(30) NOT NULL, 
		"CW_VERSION" INTEGER NOT NULL, 
		"CW_LOAD_ID" INTEGER NOT NULL, 
		"PK_KNB1" VARGRAPHIC(250) NOT NULL, 
		"FK_KNA1_EKVBD" VARGRAPHIC(250), 
		"FK_KNA1_KNRZB" VARGRAPHIC(250), 
		"FK_KNA1_KNRZE" VARGRAPHIC(250), 
		"FK_KNA1_KUNNR" VARGRAPHIC(250), 
		"FK_KNA1_REMIT" VARGRAPHIC(250)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."KNVP" (
		"MANDT" VARGRAPHIC(6), 
		"KUNNR" VARGRAPHIC(20), 
		"VKORG" VARGRAPHIC(8), 
		"VTWEG" VARGRAPHIC(4), 
		"SPART" VARGRAPHIC(4), 
		"PARVW" VARGRAPHIC(4), 
		"PARZA" VARGRAPHIC(6), 
		"KUNN2" VARGRAPHIC(20), 
		"LIFNR" VARGRAPHIC(20), 
		"PERNR" VARGRAPHIC(16), 
		"PARNR" VARGRAPHIC(20), 
		"KNREF" VARGRAPHIC(60), 
		"DEFPA" VARGRAPHIC(2), 
		"CW_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"CW_LEGACY_UK" VARGRAPHIC(120) NOT NULL, 
		"CW_LOB" VARGRAPHIC(10) NOT NULL, 
		"CW_RLOUT" VARGRAPHIC(30) NOT NULL, 
		"CW_CATEGORY" VARGRAPHIC(30) NOT NULL, 
		"CW_VERSION" INTEGER NOT NULL, 
		"CW_LOAD_ID" INTEGER NOT NULL, 
		"PK_KNVP" VARGRAPHIC(250) NOT NULL, 
		"FK_KNA1_KUNN2" VARGRAPHIC(250), 
		"FK_KNA1_KUNNR" VARGRAPHIC(250)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."KNVV" (
		"MANDT" VARGRAPHIC(6), 
		"KUNNR" VARGRAPHIC(20), 
		"VKORG" VARGRAPHIC(8), 
		"VTWEG" VARGRAPHIC(4), 
		"SPART" VARGRAPHIC(4), 
		"ERNAM" VARGRAPHIC(24), 
		"ERDAT" VARGRAPHIC(16), 
		"BEGRU" VARGRAPHIC(8), 
		"LOEVM" VARGRAPHIC(2), 
		"VERSG" VARGRAPHIC(2), 
		"AUFSD" VARGRAPHIC(4), 
		"KALKS" VARGRAPHIC(2), 
		"KDGRP" VARGRAPHIC(4), 
		"BZIRK" VARGRAPHIC(12), 
		"KONDA" VARGRAPHIC(4), 
		"PLTYP" VARGRAPHIC(4), 
		"AWAHR" VARGRAPHIC(6), 
		"INCO1" VARGRAPHIC(6), 
		"INCO2" VARGRAPHIC(56), 
		"LIFSD" VARGRAPHIC(4), 
		"AUTLF" VARGRAPHIC(2), 
		"ANTLF" VARGRAPHIC(6), 
		"KZTLF" VARGRAPHIC(2), 
		"KZAZU" VARGRAPHIC(2), 
		"CHSPL" VARGRAPHIC(2), 
		"LPRIO" VARGRAPHIC(4), 
		"EIKTO" VARGRAPHIC(24), 
		"VSBED" VARGRAPHIC(4), 
		"FAKSD" VARGRAPHIC(4), 
		"MRNKZ" VARGRAPHIC(2), 
		"PERFK" VARGRAPHIC(4), 
		"PERRL" VARGRAPHIC(4), 
		"KVAKZ" VARGRAPHIC(2), 
		"KVAWT" VARGRAPHIC(30), 
		"WAERS" VARGRAPHIC(10), 
		"KLABC" VARGRAPHIC(4), 
		"KTGRD" VARGRAPHIC(4), 
		"ZTERM" VARGRAPHIC(8), 
		"VWERK" VARGRAPHIC(8), 
		"VKGRP" VARGRAPHIC(6), 
		"VKBUR" VARGRAPHIC(8), 
		"VSORT" VARGRAPHIC(20), 
		"KVGR1" VARGRAPHIC(6), 
		"KVGR2" VARGRAPHIC(6), 
		"KVGR3" VARGRAPHIC(6), 
		"KVGR4" VARGRAPHIC(6), 
		"KVGR5" VARGRAPHIC(6), 
		"BOKRE" VARGRAPHIC(2), 
		"BOIDT" VARGRAPHIC(16), 
		"KURST" VARGRAPHIC(8), 
		"PRFRE" VARGRAPHIC(2), 
		"PRAT1" VARGRAPHIC(2), 
		"PRAT2" VARGRAPHIC(2), 
		"PRAT3" VARGRAPHIC(2), 
		"PRAT4" VARGRAPHIC(2), 
		"PRAT5" VARGRAPHIC(2), 
		"PRAT6" VARGRAPHIC(2), 
		"PRAT7" VARGRAPHIC(2), 
		"PRAT8" VARGRAPHIC(2), 
		"PRAT9" VARGRAPHIC(2), 
		"PRATA" VARGRAPHIC(2), 
		"KABSS" VARGRAPHIC(8), 
		"KKBER" VARGRAPHIC(8), 
		"CASSD" VARGRAPHIC(4), 
		"RDOFF" VARGRAPHIC(2), 
		"AGREL" VARGRAPHIC(2), 
		"MEGRU" VARGRAPHIC(8), 
		"UEBTO" VARGRAPHIC(10), 
		"UNTTO" VARGRAPHIC(10), 
		"UEBTK" VARGRAPHIC(2), 
		"PVKSM" VARGRAPHIC(4), 
		"PODKZ" VARGRAPHIC(2), 
		"PODTG" VARGRAPHIC(26), 
		"BLIND" VARGRAPHIC(2), 
		"CARRIER_NOTIF" VARGRAPHIC(2), 
		"ABEV1_EMLGPFAND" VARGRAPHIC(2), 
		"ABEV1_EMLGFORTS" VARGRAPHIC(2), 
		"CW_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"CW_LEGACY_UK" VARGRAPHIC(120) NOT NULL, 
		"CW_LOB" VARGRAPHIC(10) NOT NULL, 
		"CW_RLOUT" VARGRAPHIC(30) NOT NULL, 
		"CW_CATEGORY" VARGRAPHIC(30) NOT NULL, 
		"CW_VERSION" INTEGER NOT NULL, 
		"CW_LOAD_ID" INTEGER NOT NULL, 
		"PK_KNVV" VARGRAPHIC(250) NOT NULL, 
		"FK_KNA1_KUNNR" VARGRAPHIC(250)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_BUSTYPE" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_GESTYP" VARGRAPHIC(60) NOT NULL, 
		"TARGET_GESTYP" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_FMFGT_ALC" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_ALC" VARGRAPHIC(16) NOT NULL, 
		"TARGET_ALC" VARGRAPHIC(16)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_FMFGT_PO" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_PMT_OFFICE" VARGRAPHIC(10) NOT NULL, 
		"TARGET_PMT_OFFICE" VARGRAPHIC(10)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_INDUSTYPE" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_INDTYPE" VARGRAPHIC(60) NOT NULL, 
		"TARGET_INDTYPE" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_J_1ADTYP" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_BUKRS" VARGRAPHIC(8) NOT NULL, 
		"SOURCE_J_1ADTYP" VARGRAPHIC(4) NOT NULL, 
		"TARGET_BUKRS" VARGRAPHIC(8), 
		"TARGET_J_1ADTYP" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_J_1ATODC" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_J_1ATODC" VARGRAPHIC(4) NOT NULL, 
		"TARGET_J_1ATODC" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_J_1BATL1" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_TAXLAW" VARGRAPHIC(6) NOT NULL, 
		"TARGET_TAXLAW" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_J_1BATL2" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_TAXLAW" VARGRAPHIC(6) NOT NULL, 
		"TARGET_TAXLAW" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_J_1BTXSTG" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_STGRP" VARGRAPHIC(6) NOT NULL, 
		"TARGET_STGRP" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_MARA" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_MATNR" VARGRAPHIC(36) NOT NULL, 
		"TARGET_MATNR" VARGRAPHIC(36)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T000" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T001" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_BUKRS" VARGRAPHIC(8) NOT NULL, 
		"TARGET_BUKRS" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T001S" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_BUKRS" VARGRAPHIC(8) NOT NULL, 
		"SOURCE_BUSAB" VARGRAPHIC(4) NOT NULL, 
		"TARGET_BUKRS" VARGRAPHIC(8), 
		"TARGET_BUSAB" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T001W" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_WERKS" VARGRAPHIC(8) NOT NULL, 
		"TARGET_WERKS" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T002" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_SPRAS" VARGRAPHIC(2) NOT NULL, 
		"TARGET_SPRAS" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T005" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_LAND1" VARGRAPHIC(6) NOT NULL, 
		"TARGET_LAND1" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T005E" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_LAND1" VARGRAPHIC(6) NOT NULL, 
		"SOURCE_REGIO" VARGRAPHIC(6) NOT NULL, 
		"SOURCE_COUNC" VARGRAPHIC(6) NOT NULL, 
		"TARGET_LAND1" VARGRAPHIC(6), 
		"TARGET_REGIO" VARGRAPHIC(6), 
		"TARGET_COUNC" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T005G" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_LAND1" VARGRAPHIC(6) NOT NULL, 
		"SOURCE_REGIO" VARGRAPHIC(6) NOT NULL, 
		"SOURCE_CITYC" VARGRAPHIC(8) NOT NULL, 
		"TARGET_LAND1" VARGRAPHIC(6), 
		"TARGET_REGIO" VARGRAPHIC(6), 
		"TARGET_CITYC" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T005S" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_LAND1" VARGRAPHIC(6) NOT NULL, 
		"SOURCE_BLAND" VARGRAPHIC(6) NOT NULL, 
		"TARGET_LAND1" VARGRAPHIC(6), 
		"TARGET_BLAND" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T006" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_MSEHI" VARGRAPHIC(6) NOT NULL, 
		"TARGET_MSEHI" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T008" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_ZAHLS" VARGRAPHIC(2) NOT NULL, 
		"TARGET_ZAHLS" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T009" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_PERIV" VARGRAPHIC(4) NOT NULL, 
		"TARGET_PERIV" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T014" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KKBER" VARGRAPHIC(8) NOT NULL, 
		"TARGET_KKBER" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T016" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_BRSCH" VARGRAPHIC(8) NOT NULL, 
		"TARGET_BRSCH" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T035" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_GRUPP" VARGRAPHIC(20) NOT NULL, 
		"TARGET_GRUPP" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T042F" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_UZAWE" VARGRAPHIC(4) NOT NULL, 
		"TARGET_UZAWE" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T043G" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_BUKRS" VARGRAPHIC(8) NOT NULL, 
		"SOURCE_TOGRU" VARGRAPHIC(8) NOT NULL, 
		"TARGET_BUKRS" VARGRAPHIC(8), 
		"TARGET_TOGRU" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T047R" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_MGRUP" VARGRAPHIC(4) NOT NULL, 
		"TARGET_MGRUP" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T048K" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_XAUSZ" VARGRAPHIC(2) NOT NULL, 
		"TARGET_XAUSZ" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T049L" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_BUKRS" VARGRAPHIC(8) NOT NULL, 
		"SOURCE_LOCKB" VARGRAPHIC(14) NOT NULL, 
		"TARGET_BUKRS" VARGRAPHIC(8), 
		"TARGET_LOCKB" VARGRAPHIC(14)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T052A" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_URLID" VARGRAPHIC(8) NOT NULL, 
		"TARGET_URLID" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T053A" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_SREGL" VARGRAPHIC(6) NOT NULL, 
		"TARGET_SREGL" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T053V" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_VRSDG" VARGRAPHIC(6) NOT NULL, 
		"TARGET_VRSDG" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T056" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_VZSKZ" VARGRAPHIC(4) NOT NULL, 
		"TARGET_VZSKZ" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T077D" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KTOKD" VARGRAPHIC(8) NOT NULL, 
		"TARGET_KTOKD" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T151" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KDGRP" VARGRAPHIC(4) NOT NULL, 
		"TARGET_KDGRP" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T171" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_BZIRK" VARGRAPHIC(12) NOT NULL, 
		"TARGET_BZIRK" VARGRAPHIC(12)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T188" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KONDA" VARGRAPHIC(4) NOT NULL, 
		"TARGET_KONDA" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T189" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_PLTYP" VARGRAPHIC(4) NOT NULL, 
		"TARGET_PLTYP" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T691P" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KABSS" VARGRAPHIC(8) NOT NULL, 
		"TARGET_KABSS" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_T880" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_RCOMP" VARGRAPHIC(12) NOT NULL, 
		"TARGET_RCOMP" VARGRAPHIC(12)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TBRC" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_BRACO" VARGRAPHIC(20) NOT NULL, 
		"TARGET_BRACO" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TCURC" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_WAERS" VARGRAPHIC(10) NOT NULL, 
		"TARGET_WAERS" VARGRAPHIC(10)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TCURV" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KURST" VARGRAPHIC(8) NOT NULL, 
		"TARGET_KURST" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TFACD" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_IDENT" VARGRAPHIC(4) NOT NULL, 
		"TARGET_IDENT" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TINC" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_INCO1" VARGRAPHIC(6) NOT NULL, 
		"TARGET_INCO1" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TKUKL" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KUKLA" VARGRAPHIC(4) NOT NULL, 
		"TARGET_KUKLA" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TNLS" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_NIELS" VARGRAPHIC(4) NOT NULL, 
		"TARGET_NIELS" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TPAR" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_PARVW" VARGRAPHIC(4) NOT NULL, 
		"TARGET_PARVW" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TPRIO" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_LPRIO" VARGRAPHIC(4) NOT NULL, 
		"TARGET_LPRIO" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TPVD" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_PVKSM" VARGRAPHIC(4) NOT NULL, 
		"TARGET_PVKSM" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TSPA" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_SPART" VARGRAPHIC(4) NOT NULL, 
		"TARGET_SPART" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVAST" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_SPRAS" VARGRAPHIC(2) NOT NULL, 
		"SOURCE_AUFSP" VARGRAPHIC(4) NOT NULL, 
		"TARGET_SPRAS" VARGRAPHIC(2), 
		"TARGET_AUFSP" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVBUR" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_VKBUR" VARGRAPHIC(8) NOT NULL, 
		"TARGET_VKBUR" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVBVK" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_VKBUR" VARGRAPHIC(8) NOT NULL, 
		"SOURCE_VKGRP" VARGRAPHIC(6) NOT NULL, 
		"TARGET_VKBUR" VARGRAPHIC(8), 
		"TARGET_VKGRP" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVFS" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_FAKSP" VARGRAPHIC(4) NOT NULL, 
		"TARGET_FAKSP" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVGF" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_GFORM" VARGRAPHIC(4) NOT NULL, 
		"TARGET_GFORM" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVK0" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KATR10" VARGRAPHIC(6) NOT NULL, 
		"TARGET_KATR10" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVK1" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KATR1" VARGRAPHIC(4) NOT NULL, 
		"TARGET_KATR1" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVK2" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KATR2" VARGRAPHIC(4) NOT NULL, 
		"TARGET_KATR2" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVK3" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KATR3" VARGRAPHIC(4) NOT NULL, 
		"TARGET_KATR3" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVK4" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KATR4" VARGRAPHIC(4) NOT NULL, 
		"TARGET_KATR4" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVK5" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KATR5" VARGRAPHIC(4) NOT NULL, 
		"TARGET_KATR5" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVK6" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KATR6" VARGRAPHIC(6) NOT NULL, 
		"TARGET_KATR6" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVK7" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KATR7" VARGRAPHIC(6) NOT NULL, 
		"TARGET_KATR7" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVK8" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KATR8" VARGRAPHIC(6) NOT NULL, 
		"TARGET_KATR8" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVK9" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KATR9" VARGRAPHIC(6) NOT NULL, 
		"TARGET_KATR9" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVKD" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KALKS" VARGRAPHIC(2) NOT NULL, 
		"TARGET_KALKS" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVKGG" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KDKGR" VARGRAPHIC(4) NOT NULL, 
		"TARGET_KDKGR" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVKO" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_VKORG" VARGRAPHIC(8) NOT NULL, 
		"TARGET_VKORG" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVKT" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KTGRD" VARGRAPHIC(4) NOT NULL, 
		"TARGET_KTGRD" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVLS" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_LIFSP" VARGRAPHIC(4) NOT NULL, 
		"TARGET_LIFSP" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVLV" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_ABRVW" VARGRAPHIC(6) NOT NULL, 
		"TARGET_ABRVW" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVSB" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_VSBED" VARGRAPHIC(4) NOT NULL, 
		"TARGET_VSBED" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVSD" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_STGKU" VARGRAPHIC(2) NOT NULL, 
		"TARGET_STGKU" VARGRAPHIC(2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVTW" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_VTWEG" VARGRAPHIC(4) NOT NULL, 
		"TARGET_VTWEG" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVV1" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KVGR1" VARGRAPHIC(6) NOT NULL, 
		"TARGET_KVGR1" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVV2" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KVGR2" VARGRAPHIC(6) NOT NULL, 
		"TARGET_KVGR2" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVV3" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KVGR3" VARGRAPHIC(6) NOT NULL, 
		"TARGET_KVGR3" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVV4" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KVGR4" VARGRAPHIC(6) NOT NULL, 
		"TARGET_KVGR4" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TVV5" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KVGR5" VARGRAPHIC(6) NOT NULL, 
		"TARGET_KVGR5" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TWEK" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_KUNGR" VARGRAPHIC(20) NOT NULL, 
		"TARGET_KUNGR" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TZGR" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_ZGRUP" VARGRAPHIC(4) NOT NULL, 
		"TARGET_ZGRUP" VARGRAPHIC(4)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TZONE" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_LAND1" VARGRAPHIC(6) NOT NULL, 
		"SOURCE_ZONE1" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LAND1" VARGRAPHIC(6), 
		"TARGET_ZONE1" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_TZUN" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_ZUAWA" VARGRAPHIC(6) NOT NULL, 
		"TARGET_ZUAWA" VARGRAPHIC(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_VBUK" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_VBELN" VARGRAPHIC(20) NOT NULL, 
		"TARGET_VBELN" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT_VBWF08" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE_FRGRP" VARGRAPHIC(8) NOT NULL, 
		"TARGET_FRGRP" VARGRAPHIC(8)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "ALG0"."TT__VSO_R_DPOINT" (
		"SOURCE_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"TARGET_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"SOURCE_DESCRIPTION" VARGRAPHIC(250), 
		"SOURCE__VSO_R_DPOINT" VARGRAPHIC(20) NOT NULL, 
		"TARGET__VSO_R_DPOINT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

ALTER TABLE "ALG0"."DTT_AWAHR" ADD CONSTRAINT "DTT_AWAHR_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_AWAHR")!

ALTER TABLE "ALG0"."DTT_DEAR3" ADD CONSTRAINT "DTT_DEAR3_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_DEAR3")!

ALTER TABLE "ALG0"."DTT_DTAMS" ADD CONSTRAINT "DTT_DTAMS_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_DTAMS")!

ALTER TABLE "ALG0"."DTT_DUEFL_BKPF" ADD CONSTRAINT "DTT_DUEFL_BKPF_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_DUEFL_BKPF")!

ALTER TABLE "ALG0"."DTT_J_1BINDUS1" ADD CONSTRAINT "DTT_J_1BINDUS1_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_J_1BINDUS1")!

ALTER TABLE "ALG0"."DTT_KZTLF" ADD CONSTRAINT "DTT_KZTLF_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KZTLF")!

ALTER TABLE "ALG0"."DTT_PRATK" ADD CONSTRAINT "DTT_PRATK_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_PRATK")!

ALTER TABLE "ALG0"."DTT_QKZ" ADD CONSTRAINT "DTT_QKZ_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_QKZ")!

ALTER TABLE "ALG0"."DTT_STKZA" ADD CONSTRAINT "DTT_STKZA_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_STKZA")!

ALTER TABLE "ALG0"."DTT_STKZN" ADD CONSTRAINT "DTT_STKZN_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_STKZN")!

ALTER TABLE "ALG0"."DTT_XFELD" ADD CONSTRAINT "DTT_XFELD_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_XFELD")!

ALTER TABLE "ALG0"."DTT_ZINRT" ADD CONSTRAINT "DTT_ZINRT_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_ZINRT")!

ALTER TABLE "ALG0"."DTT__BEV1_EMGFORTS" ADD CONSTRAINT "DTT__BEV1_EMGFORTS_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE__BEV1_EMGFORTS")!

ALTER TABLE "ALG0"."DTT__BEV1_EMGPFAND" ADD CONSTRAINT "DTT__BEV1_EMGPFAND_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE__BEV1_EMGPFAND")!

ALTER TABLE "ALG0"."DTT__VSO_M_LOAD_PREF" ADD CONSTRAINT "DTT__VSO_M_LOAD_PREF_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE__VSO_M_LOAD_PREF")!

ALTER TABLE "ALG0"."DTT__VSO_M_SIDE_PREF" ADD CONSTRAINT "DTT__VSO_M_SIDE_PREF_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE__VSO_M_SIDE_PREF")!

ALTER TABLE "ALG0"."DTT__VSO_M_XFIELD" ADD CONSTRAINT "DTT__VSO_M_XFIELD_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE__VSO_M_XFIELD")!

ALTER TABLE "ALG0"."KNA1" ADD CONSTRAINT "KNA1_PK" PRIMARY KEY
	("PK_KNA1")!

ALTER TABLE "ALG0"."KNB1" ADD CONSTRAINT "KNB1_PK" PRIMARY KEY
	("PK_KNB1")!

ALTER TABLE "ALG0"."KNVP" ADD CONSTRAINT "KNVP_PK" PRIMARY KEY
	("PK_KNVP")!

ALTER TABLE "ALG0"."KNVV" ADD CONSTRAINT "KNVV_PK" PRIMARY KEY
	("PK_KNVV")!

ALTER TABLE "ALG0"."TT_BUSTYPE" ADD CONSTRAINT "TT_BUSTYPE_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_GESTYP")!

ALTER TABLE "ALG0"."TT_FMFGT_ALC" ADD CONSTRAINT "TT_FMFGT_ALC_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_ALC")!

ALTER TABLE "ALG0"."TT_FMFGT_PO" ADD CONSTRAINT "TT_FMFGT_PO_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_PMT_OFFICE")!

ALTER TABLE "ALG0"."TT_INDUSTYPE" ADD CONSTRAINT "TT_INDUSTYPE_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_INDTYPE")!

ALTER TABLE "ALG0"."TT_J_1ADTYP" ADD CONSTRAINT "TT_J_1ADTYP_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_BUKRS", 
	 "SOURCE_J_1ADTYP")!

ALTER TABLE "ALG0"."TT_J_1ATODC" ADD CONSTRAINT "TT_J_1ATODC_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_J_1ATODC")!

ALTER TABLE "ALG0"."TT_J_1BATL1" ADD CONSTRAINT "TT_J_1BATL1_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_TAXLAW")!

ALTER TABLE "ALG0"."TT_J_1BATL2" ADD CONSTRAINT "TT_J_1BATL2_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_TAXLAW")!

ALTER TABLE "ALG0"."TT_J_1BTXSTG" ADD CONSTRAINT "TT_J_1BTXSTG_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_STGRP")!

ALTER TABLE "ALG0"."TT_MARA" ADD CONSTRAINT "TT_MARA_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_MATNR")!

ALTER TABLE "ALG0"."TT_T000" ADD CONSTRAINT "TT_T000_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID")!

ALTER TABLE "ALG0"."TT_T001" ADD CONSTRAINT "TT_T001_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_BUKRS")!

ALTER TABLE "ALG0"."TT_T001S" ADD CONSTRAINT "TT_T001S_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_BUKRS", 
	 "SOURCE_BUSAB")!

ALTER TABLE "ALG0"."TT_T001W" ADD CONSTRAINT "TT_T001W_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_WERKS")!

ALTER TABLE "ALG0"."TT_T002" ADD CONSTRAINT "TT_T002_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_SPRAS")!

ALTER TABLE "ALG0"."TT_T005" ADD CONSTRAINT "TT_T005_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_LAND1")!

ALTER TABLE "ALG0"."TT_T005E" ADD CONSTRAINT "TT_T005E_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_LAND1", 
	 "SOURCE_REGIO", 
	 "SOURCE_COUNC")!

ALTER TABLE "ALG0"."TT_T005G" ADD CONSTRAINT "TT_T005G_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_LAND1", 
	 "SOURCE_REGIO", 
	 "SOURCE_CITYC")!

ALTER TABLE "ALG0"."TT_T005S" ADD CONSTRAINT "TT_T005S_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_LAND1", 
	 "SOURCE_BLAND")!

ALTER TABLE "ALG0"."TT_T006" ADD CONSTRAINT "TT_T006_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_MSEHI")!

ALTER TABLE "ALG0"."TT_T008" ADD CONSTRAINT "TT_T008_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_ZAHLS")!

ALTER TABLE "ALG0"."TT_T009" ADD CONSTRAINT "TT_T009_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_PERIV")!

ALTER TABLE "ALG0"."TT_T014" ADD CONSTRAINT "TT_T014_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KKBER")!

ALTER TABLE "ALG0"."TT_T016" ADD CONSTRAINT "TT_T016_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_BRSCH")!

ALTER TABLE "ALG0"."TT_T035" ADD CONSTRAINT "TT_T035_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_GRUPP")!

ALTER TABLE "ALG0"."TT_T042F" ADD CONSTRAINT "TT_T042F_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_UZAWE")!

ALTER TABLE "ALG0"."TT_T043G" ADD CONSTRAINT "TT_T043G_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_BUKRS", 
	 "SOURCE_TOGRU")!

ALTER TABLE "ALG0"."TT_T047R" ADD CONSTRAINT "TT_T047R_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_MGRUP")!

ALTER TABLE "ALG0"."TT_T048K" ADD CONSTRAINT "TT_T048K_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_XAUSZ")!

ALTER TABLE "ALG0"."TT_T049L" ADD CONSTRAINT "TT_T049L_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_BUKRS", 
	 "SOURCE_LOCKB")!

ALTER TABLE "ALG0"."TT_T052A" ADD CONSTRAINT "TT_T052A_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_URLID")!

ALTER TABLE "ALG0"."TT_T053A" ADD CONSTRAINT "TT_T053A_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_SREGL")!

ALTER TABLE "ALG0"."TT_T053V" ADD CONSTRAINT "TT_T053V_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_VRSDG")!

ALTER TABLE "ALG0"."TT_T056" ADD CONSTRAINT "TT_T056_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_VZSKZ")!

ALTER TABLE "ALG0"."TT_T077D" ADD CONSTRAINT "TT_T077D_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KTOKD")!

ALTER TABLE "ALG0"."TT_T151" ADD CONSTRAINT "TT_T151_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KDGRP")!

ALTER TABLE "ALG0"."TT_T171" ADD CONSTRAINT "TT_T171_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_BZIRK")!

ALTER TABLE "ALG0"."TT_T188" ADD CONSTRAINT "TT_T188_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KONDA")!

ALTER TABLE "ALG0"."TT_T189" ADD CONSTRAINT "TT_T189_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_PLTYP")!

ALTER TABLE "ALG0"."TT_T691P" ADD CONSTRAINT "TT_T691P_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KABSS")!

ALTER TABLE "ALG0"."TT_T880" ADD CONSTRAINT "TT_T880_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_RCOMP")!

ALTER TABLE "ALG0"."TT_TBRC" ADD CONSTRAINT "TT_TBRC_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_BRACO")!

ALTER TABLE "ALG0"."TT_TCURC" ADD CONSTRAINT "TT_TCURC_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_WAERS")!

ALTER TABLE "ALG0"."TT_TCURV" ADD CONSTRAINT "TT_TCURV_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KURST")!

ALTER TABLE "ALG0"."TT_TFACD" ADD CONSTRAINT "TT_TFACD_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_IDENT")!

ALTER TABLE "ALG0"."TT_TINC" ADD CONSTRAINT "TT_TINC_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_INCO1")!

ALTER TABLE "ALG0"."TT_TKUKL" ADD CONSTRAINT "TT_TKUKL_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KUKLA")!

ALTER TABLE "ALG0"."TT_TNLS" ADD CONSTRAINT "TT_TNLS_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_NIELS")!

ALTER TABLE "ALG0"."TT_TPAR" ADD CONSTRAINT "TT_TPAR_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_PARVW")!

ALTER TABLE "ALG0"."TT_TPRIO" ADD CONSTRAINT "TT_TPRIO_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_LPRIO")!

ALTER TABLE "ALG0"."TT_TPVD" ADD CONSTRAINT "TT_TPVD_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_PVKSM")!

ALTER TABLE "ALG0"."TT_TSPA" ADD CONSTRAINT "TT_TSPA_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_SPART")!

ALTER TABLE "ALG0"."TT_TVAST" ADD CONSTRAINT "TT_TVAST_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_SPRAS", 
	 "SOURCE_AUFSP")!

ALTER TABLE "ALG0"."TT_TVBUR" ADD CONSTRAINT "TT_TVBUR_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_VKBUR")!

ALTER TABLE "ALG0"."TT_TVBVK" ADD CONSTRAINT "TT_TVBVK_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_VKBUR", 
	 "SOURCE_VKGRP")!

ALTER TABLE "ALG0"."TT_TVFS" ADD CONSTRAINT "TT_TVFS_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_FAKSP")!

ALTER TABLE "ALG0"."TT_TVGF" ADD CONSTRAINT "TT_TVGF_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_GFORM")!

ALTER TABLE "ALG0"."TT_TVK0" ADD CONSTRAINT "TT_TVK0_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KATR10")!

ALTER TABLE "ALG0"."TT_TVK1" ADD CONSTRAINT "TT_TVK1_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KATR1")!

ALTER TABLE "ALG0"."TT_TVK2" ADD CONSTRAINT "TT_TVK2_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KATR2")!

ALTER TABLE "ALG0"."TT_TVK3" ADD CONSTRAINT "TT_TVK3_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KATR3")!

ALTER TABLE "ALG0"."TT_TVK4" ADD CONSTRAINT "TT_TVK4_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KATR4")!

ALTER TABLE "ALG0"."TT_TVK5" ADD CONSTRAINT "TT_TVK5_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KATR5")!

ALTER TABLE "ALG0"."TT_TVK6" ADD CONSTRAINT "TT_TVK6_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KATR6")!

ALTER TABLE "ALG0"."TT_TVK7" ADD CONSTRAINT "TT_TVK7_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KATR7")!

ALTER TABLE "ALG0"."TT_TVK8" ADD CONSTRAINT "TT_TVK8_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KATR8")!

ALTER TABLE "ALG0"."TT_TVK9" ADD CONSTRAINT "TT_TVK9_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KATR9")!

ALTER TABLE "ALG0"."TT_TVKD" ADD CONSTRAINT "TT_TVKD_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KALKS")!

ALTER TABLE "ALG0"."TT_TVKGG" ADD CONSTRAINT "TT_TVKGG_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KDKGR")!

ALTER TABLE "ALG0"."TT_TVKO" ADD CONSTRAINT "TT_TVKO_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_VKORG")!

ALTER TABLE "ALG0"."TT_TVKT" ADD CONSTRAINT "TT_TVKT_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KTGRD")!

ALTER TABLE "ALG0"."TT_TVLS" ADD CONSTRAINT "TT_TVLS_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_LIFSP")!

ALTER TABLE "ALG0"."TT_TVLV" ADD CONSTRAINT "TT_TVLV_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_ABRVW")!

ALTER TABLE "ALG0"."TT_TVSB" ADD CONSTRAINT "TT_TVSB_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_VSBED")!

ALTER TABLE "ALG0"."TT_TVSD" ADD CONSTRAINT "TT_TVSD_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_STGKU")!

ALTER TABLE "ALG0"."TT_TVTW" ADD CONSTRAINT "TT_TVTW_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_VTWEG")!

ALTER TABLE "ALG0"."TT_TVV1" ADD CONSTRAINT "TT_TVV1_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KVGR1")!

ALTER TABLE "ALG0"."TT_TVV2" ADD CONSTRAINT "TT_TVV2_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KVGR2")!

ALTER TABLE "ALG0"."TT_TVV3" ADD CONSTRAINT "TT_TVV3_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KVGR3")!

ALTER TABLE "ALG0"."TT_TVV4" ADD CONSTRAINT "TT_TVV4_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KVGR4")!

ALTER TABLE "ALG0"."TT_TVV5" ADD CONSTRAINT "TT_TVV5_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KVGR5")!

ALTER TABLE "ALG0"."TT_TWEK" ADD CONSTRAINT "TT_TWEK_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_KUNGR")!

ALTER TABLE "ALG0"."TT_TZGR" ADD CONSTRAINT "TT_TZGR_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_ZGRUP")!

ALTER TABLE "ALG0"."TT_TZONE" ADD CONSTRAINT "TT_TZONE_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_LAND1", 
	 "SOURCE_ZONE1")!

ALTER TABLE "ALG0"."TT_TZUN" ADD CONSTRAINT "TT_TZUN_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_ZUAWA")!

ALTER TABLE "ALG0"."TT_VBUK" ADD CONSTRAINT "TT_VBUK_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_VBELN")!

ALTER TABLE "ALG0"."TT_VBWF08" ADD CONSTRAINT "TT_VBWF08_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE_FRGRP")!

ALTER TABLE "ALG0"."TT__VSO_R_DPOINT" ADD CONSTRAINT "TT__VSO_R_DPOINT_PK" PRIMARY KEY
	("SOURCE_LEGACY_ID", 
	 "TARGET_LEGACY_ID", 
	 "SOURCE__VSO_R_DPOINT")!

