--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA "PLD"!

CREATE TABLE "PLD"."CT_AVSO_R_DPOINT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"AVSO_R_DPOINT" VARGRAPHIC(10) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_BUSTYPE" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"GESTYP" VARGRAPHIC(30) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_FMFGT_ALC" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"ALC" VARGRAPHIC(8) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_FMFGT_PO" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"PMT_OFFICE" VARGRAPHIC(5) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_INDUSTYPE" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"INDTYPE" VARGRAPHIC(30) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_J_1ADTYP" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"BUKRS" VARGRAPHIC(4) NOT NULL, 
		"J_1ADTYP" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_J_1ATODC" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"J_1ATODC" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_J_1BATL1" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"TAXLAW" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_J_1BATL2" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"TAXLAW" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_J_1BTXSTG" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"STGRP" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_MARA" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"MATNR" VARGRAPHIC(18) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T000" (
		"MANDT" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T001" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"BUKRS" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T001S" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"BUKRS" VARGRAPHIC(4) NOT NULL, 
		"BUSAB" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T001W" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"WERKS" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T002" (
		"SPRAS" VARGRAPHIC(1) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T005" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"LAND1" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T005E" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"LAND1" VARGRAPHIC(3) NOT NULL, 
		"REGIO" VARGRAPHIC(3) NOT NULL, 
		"COUNC" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T005G" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"LAND1" VARGRAPHIC(3) NOT NULL, 
		"REGIO" VARGRAPHIC(3) NOT NULL, 
		"CITYC" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T005S" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"LAND1" VARGRAPHIC(3) NOT NULL, 
		"BLAND" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T006" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"MSEHI" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T008" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"ZAHLS" VARGRAPHIC(1) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T009" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"PERIV" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T014" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KKBER" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T016" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"BRSCH" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T035" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"GRUPP" VARGRAPHIC(10) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T042F" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"UZAWE" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T043G" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"BUKRS" VARGRAPHIC(4) NOT NULL, 
		"TOGRU" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T047R" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"MGRUP" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T048K" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"XAUSZ" VARGRAPHIC(1) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T049L" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"BUKRS" VARGRAPHIC(4) NOT NULL, 
		"LOCKB" VARGRAPHIC(7) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T052A" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"URLID" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T053A" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SREGL" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T053V" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"VRSDG" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T056" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"VZSKZ" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T077D" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KTOKD" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T151" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KDGRP" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T171" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"BZIRK" VARGRAPHIC(6) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T188" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KONDA" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T189" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"PLTYP" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T691P" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KABSS" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_T880" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"RCOMP" VARGRAPHIC(6) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TBRC" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"BRACO" VARGRAPHIC(10) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TCURC" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"WAERS" VARGRAPHIC(5) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TCURV" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KURST" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TFACD" (
		"IDENT" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TINC" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"INCO1" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TKUKL" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KUKLA" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TNLS" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"NIELS" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TPAR" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"PARVW" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TPRIO" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"LPRIO" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TPVD" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"PVKSM" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TSPA" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPART" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVAST" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"AUFSP" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVBUR" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"VKBUR" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVBVK" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"VKBUR" VARGRAPHIC(4) NOT NULL, 
		"VKGRP" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVFS" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"FAKSP" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVGF" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"GFORM" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVK0" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KATR10" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVK1" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KATR1" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVK2" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KATR2" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVK3" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KATR3" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVK4" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KATR4" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVK5" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KATR5" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVK6" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KATR6" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVK7" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KATR7" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVK8" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KATR8" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVK9" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KATR9" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVKD" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KALKS" VARGRAPHIC(1) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVKGG" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KDKGR" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVKO" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"VKORG" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVKT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KTGRD" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVLS" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"LIFSP" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVLV" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"ABRVW" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVSB" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"VSBED" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVSD" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"STGKU" VARGRAPHIC(1) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVTW" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"VTWEG" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVV1" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KVGR1" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVV2" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KVGR2" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVV3" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KVGR3" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVV4" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KVGR4" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TVV5" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KVGR5" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TWEK" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"KUNGR" VARGRAPHIC(10) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TZGR" (
		"ZGRUP" VARGRAPHIC(2) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TZONE" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"LAND1" VARGRAPHIC(3) NOT NULL, 
		"ZONE1" VARGRAPHIC(10) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_TZUN" (
		"ZUAWA" VARGRAPHIC(3) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_VBUK" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"VBELN" VARGRAPHIC(10) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."CT_VBWF08" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"FRGRP" VARGRAPHIC(4) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_AWAHR" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_DEAR3" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_DTAMS" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_DUEFL_BKPF" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_J_1BINDUS1" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_KZTLF" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_PRATK" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_QKZ" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_STKZA" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_STKZN" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_XFELD" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT_ZINRT" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT__BEV1_EMGFORTS" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT__BEV1_EMGPFAND" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT__VSO_M_LOAD_PREF" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT__VSO_M_SIDE_PREF" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."DT__VSO_M_XFIELD" (
		"VALPOS" VARGRAPHIC(4) NOT NULL, 
		"DOMVALUE_L" VARGRAPHIC(10) NOT NULL, 
		"DOMVALUE_H" VARGRAPHIC(10), 
		"DDTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."KNA1" (
		"MANDT" VARGRAPHIC(3) DEFAULT '', 
		"KUNNR" VARGRAPHIC(10) DEFAULT '', 
		"LAND1" VARGRAPHIC(3) DEFAULT '', 
		"NAME1" VARGRAPHIC(35) DEFAULT '', 
		"NAME2" VARGRAPHIC(35) DEFAULT '', 
		"ORT01" VARGRAPHIC(35) DEFAULT '', 
		"PSTLZ" VARGRAPHIC(10) DEFAULT '', 
		"REGIO" VARGRAPHIC(3) DEFAULT '', 
		"SORTL" VARGRAPHIC(10) DEFAULT '', 
		"STRAS" VARGRAPHIC(35) DEFAULT '', 
		"TELF1" VARGRAPHIC(16) DEFAULT '', 
		"TELFX" VARGRAPHIC(31) DEFAULT '', 
		"XCPDK" VARGRAPHIC(1) DEFAULT '', 
		"ADRNR" VARGRAPHIC(10) DEFAULT '', 
		"MCOD1" VARGRAPHIC(25) DEFAULT '', 
		"MCOD2" VARGRAPHIC(25) DEFAULT '', 
		"MCOD3" VARGRAPHIC(25) DEFAULT '', 
		"ANRED" VARGRAPHIC(15) DEFAULT '', 
		"AUFSD" VARGRAPHIC(2) DEFAULT '', 
		"BAHNE" VARGRAPHIC(25) DEFAULT '', 
		"BAHNS" VARGRAPHIC(25) DEFAULT '', 
		"BBBNR" VARGRAPHIC(7) DEFAULT '', 
		"BBSNR" VARGRAPHIC(5) DEFAULT '', 
		"BEGRU" VARGRAPHIC(4) DEFAULT '', 
		"BRSCH" VARGRAPHIC(4) DEFAULT '', 
		"BUBKZ" VARGRAPHIC(1) DEFAULT '', 
		"DATLT" VARGRAPHIC(14) DEFAULT '', 
		"ERDAT" VARGRAPHIC(8) DEFAULT '', 
		"ERNAM" VARGRAPHIC(12) DEFAULT '', 
		"EXABL" VARGRAPHIC(1) DEFAULT '', 
		"FAKSD" VARGRAPHIC(2) DEFAULT '', 
		"FISKN" VARGRAPHIC(10) DEFAULT '', 
		"KNAZK" VARGRAPHIC(2) DEFAULT '', 
		"KNRZA" VARGRAPHIC(10) DEFAULT '', 
		"KONZS" VARGRAPHIC(10) DEFAULT '', 
		"KTOKD" VARGRAPHIC(4) DEFAULT '', 
		"KUKLA" VARGRAPHIC(2) DEFAULT '', 
		"LIFNR" VARGRAPHIC(10) DEFAULT '', 
		"LIFSD" VARGRAPHIC(2) DEFAULT '', 
		"LOCCO" VARGRAPHIC(10) DEFAULT '', 
		"LOEVM" VARGRAPHIC(1) DEFAULT '', 
		"NAME3" VARGRAPHIC(35) DEFAULT '', 
		"NAME4" VARGRAPHIC(35) DEFAULT '', 
		"NIELS" VARGRAPHIC(2) DEFAULT '', 
		"ORT02" VARGRAPHIC(35) DEFAULT '', 
		"PFACH" VARGRAPHIC(10) DEFAULT '', 
		"PSTL2" VARGRAPHIC(10) DEFAULT '', 
		"COUNC" VARGRAPHIC(3) DEFAULT '', 
		"CITYC" VARGRAPHIC(4) DEFAULT '', 
		"RPMKR" VARGRAPHIC(5) DEFAULT '', 
		"SPERR" VARGRAPHIC(1) DEFAULT '', 
		"SPRAS" VARGRAPHIC(1) DEFAULT '', 
		"STCD1" VARGRAPHIC(16) DEFAULT '', 
		"STCD2" VARGRAPHIC(11) DEFAULT '', 
		"STKZA" VARGRAPHIC(1) DEFAULT '', 
		"STKZU" VARGRAPHIC(1) DEFAULT '', 
		"TELBX" VARGRAPHIC(15) DEFAULT '', 
		"TELF2" VARGRAPHIC(16) DEFAULT '', 
		"TELTX" VARGRAPHIC(30) DEFAULT '', 
		"TELX1" VARGRAPHIC(30) DEFAULT '', 
		"LZONE" VARGRAPHIC(10) DEFAULT '', 
		"XZEMP" VARGRAPHIC(1) DEFAULT '', 
		"VBUND" VARGRAPHIC(6) DEFAULT '', 
		"STCEG" VARGRAPHIC(20) DEFAULT '', 
		"DEAR1" VARGRAPHIC(1) DEFAULT '', 
		"DEAR2" VARGRAPHIC(1) DEFAULT '', 
		"DEAR3" VARGRAPHIC(1) DEFAULT '', 
		"DEAR4" VARGRAPHIC(1) DEFAULT '', 
		"DEAR5" VARGRAPHIC(1) DEFAULT '', 
		"GFORM" VARGRAPHIC(2) DEFAULT '', 
		"BRAN1" VARGRAPHIC(10) DEFAULT '', 
		"BRAN2" VARGRAPHIC(10) DEFAULT '', 
		"BRAN3" VARGRAPHIC(10) DEFAULT '', 
		"BRAN4" VARGRAPHIC(10) DEFAULT '', 
		"BRAN5" VARGRAPHIC(10) DEFAULT '', 
		"EKONT" VARGRAPHIC(10) DEFAULT '', 
		"UMSAT" VARGRAPHIC(10) DEFAULT '', 
		"UMJAH" VARGRAPHIC(4) DEFAULT '', 
		"UWAER" VARGRAPHIC(5) DEFAULT '', 
		"JMZAH" VARGRAPHIC(6) DEFAULT '', 
		"JMJAH" VARGRAPHIC(4) DEFAULT '', 
		"KATR1" VARGRAPHIC(2) DEFAULT '', 
		"KATR2" VARGRAPHIC(2) DEFAULT '', 
		"KATR3" VARGRAPHIC(2) DEFAULT '', 
		"KATR4" VARGRAPHIC(2) DEFAULT '', 
		"KATR5" VARGRAPHIC(2) DEFAULT '', 
		"KATR6" VARGRAPHIC(3) DEFAULT '', 
		"KATR7" VARGRAPHIC(3) DEFAULT '', 
		"KATR8" VARGRAPHIC(3) DEFAULT '', 
		"KATR9" VARGRAPHIC(3) DEFAULT '', 
		"KATR10" VARGRAPHIC(3) DEFAULT '', 
		"STKZN" VARGRAPHIC(1) DEFAULT '', 
		"UMSA1" VARGRAPHIC(17) DEFAULT '', 
		"TXJCD" VARGRAPHIC(15) DEFAULT '', 
		"PERIV" VARGRAPHIC(2) DEFAULT '', 
		"ABRVW" VARGRAPHIC(3) DEFAULT '', 
		"INSPBYDEBI" VARGRAPHIC(1) DEFAULT '', 
		"INSPATDEBI" VARGRAPHIC(1) DEFAULT '', 
		"KTOCD" VARGRAPHIC(4) DEFAULT '', 
		"PFORT" VARGRAPHIC(35) DEFAULT '', 
		"WERKS" VARGRAPHIC(4) DEFAULT '', 
		"DTAMS" VARGRAPHIC(1) DEFAULT '', 
		"DTAWS" VARGRAPHIC(2) DEFAULT '', 
		"DUEFL" VARGRAPHIC(1) DEFAULT '', 
		"HZUOR" VARGRAPHIC(2) DEFAULT '', 
		"SPERZ" VARGRAPHIC(1) DEFAULT '', 
		"ETIKG" VARGRAPHIC(10) DEFAULT '', 
		"CIVVE" VARGRAPHIC(1) DEFAULT '', 
		"MILVE" VARGRAPHIC(1) DEFAULT '', 
		"KDKG1" VARGRAPHIC(2) DEFAULT '', 
		"KDKG2" VARGRAPHIC(2) DEFAULT '', 
		"KDKG3" VARGRAPHIC(2) DEFAULT '', 
		"KDKG4" VARGRAPHIC(2) DEFAULT '', 
		"KDKG5" VARGRAPHIC(2) DEFAULT '', 
		"XKNZA" VARGRAPHIC(1) DEFAULT '', 
		"FITYP" VARGRAPHIC(2) DEFAULT '', 
		"STCDT" VARGRAPHIC(2) DEFAULT '', 
		"STCD3" VARGRAPHIC(18) DEFAULT '', 
		"STCD4" VARGRAPHIC(18) DEFAULT '', 
		"XICMS" VARGRAPHIC(1) DEFAULT '', 
		"XXIPI" VARGRAPHIC(1) DEFAULT '', 
		"XSUBT" VARGRAPHIC(3) DEFAULT '', 
		"CFOPC" VARGRAPHIC(2) DEFAULT '', 
		"TXLW1" VARGRAPHIC(3) DEFAULT '', 
		"TXLW2" VARGRAPHIC(3) DEFAULT '', 
		"CCC01" VARGRAPHIC(1) DEFAULT '', 
		"CCC02" VARGRAPHIC(1) DEFAULT '', 
		"CCC03" VARGRAPHIC(1) DEFAULT '', 
		"CCC04" VARGRAPHIC(1) DEFAULT '', 
		"CASSD" VARGRAPHIC(2) DEFAULT '', 
		"KNURL" VARGRAPHIC(132) DEFAULT '', 
		"J_1KFREPRE" VARGRAPHIC(10) DEFAULT '', 
		"J_1KFTBUS" VARGRAPHIC(30) DEFAULT '', 
		"J_1KFTIND" VARGRAPHIC(30) DEFAULT '', 
		"CONFS" VARGRAPHIC(1) DEFAULT '', 
		"UPDAT" VARGRAPHIC(8) DEFAULT '', 
		"UPTIM" VARGRAPHIC(6) DEFAULT '', 
		"NODEL" VARGRAPHIC(1) DEFAULT '', 
		"DEAR6" VARGRAPHIC(1) DEFAULT '', 
		"AVSO_R_PALHGT" VARGRAPHIC(15) DEFAULT '', 
		"AVSO_R_PAL_UL" VARGRAPHIC(3) DEFAULT '', 
		"AVSO_R_PK_MAT" VARGRAPHIC(1) DEFAULT '', 
		"AVSO_R_MATPAL" VARGRAPHIC(18) DEFAULT '', 
		"AVSO_R_I_NO_LYR" VARGRAPHIC(2) DEFAULT '', 
		"AVSO_R_ONE_MAT" VARGRAPHIC(1) DEFAULT '', 
		"AVSO_R_ONE_SORT" VARGRAPHIC(1) DEFAULT '', 
		"AVSO_R_ULD_SIDE" VARGRAPHIC(1) DEFAULT '', 
		"AVSO_R_LOAD_PREF" VARGRAPHIC(1) DEFAULT '', 
		"AVSO_R_DPOINT" VARGRAPHIC(10) DEFAULT '', 
		"ALC" VARGRAPHIC(8) DEFAULT '', 
		"PMT_OFFICE" VARGRAPHIC(5) DEFAULT '', 
		"FEE_SCHEDULE" VARGRAPHIC(4) DEFAULT '', 
		"DUNS" VARGRAPHIC(9) DEFAULT '', 
		"DUNS4" VARGRAPHIC(4) DEFAULT '', 
		"PSOFG" VARGRAPHIC(10) DEFAULT '', 
		"PSOIS" VARGRAPHIC(20) DEFAULT '', 
		"PSON1" VARGRAPHIC(35) DEFAULT '', 
		"PSON2" VARGRAPHIC(35) DEFAULT '', 
		"PSON3" VARGRAPHIC(35) DEFAULT '', 
		"PSOVN" VARGRAPHIC(35) DEFAULT '', 
		"PSOTL" VARGRAPHIC(20) DEFAULT '', 
		"PSOHS" VARGRAPHIC(6) DEFAULT '', 
		"PSOST" VARGRAPHIC(28) DEFAULT '', 
		"PSOO1" VARGRAPHIC(50) DEFAULT '', 
		"PSOO2" VARGRAPHIC(50) DEFAULT '', 
		"PSOO3" VARGRAPHIC(50) DEFAULT '', 
		"PSOO4" VARGRAPHIC(50) DEFAULT '', 
		"PSOO5" VARGRAPHIC(50) DEFAULT '', 
		"CW_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"CW_LEGACY_UK" VARGRAPHIC(120) NOT NULL, 
		"CW_LOB" VARGRAPHIC(10) NOT NULL, 
		"CW_RLOUT" VARGRAPHIC(30) NOT NULL, 
		"CW_CATEGORY" VARGRAPHIC(30) NOT NULL, 
		"CW_VERSION" INTEGER NOT NULL, 
		"CW_LOAD_ID" INTEGER NOT NULL, 
		"PK_KNA1" VARGRAPHIC(250) NOT NULL, 
		"FK_KNA1_FISKN" VARGRAPHIC(250), 
		"FK_KNA1_KNRZA" VARGRAPHIC(250)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."KNB1" (
		"MANDT" VARGRAPHIC(3) DEFAULT '', 
		"KUNNR" VARGRAPHIC(10) DEFAULT '', 
		"BUKRS" VARGRAPHIC(4) DEFAULT '', 
		"PERNR" VARGRAPHIC(8) DEFAULT '', 
		"ERDAT" VARGRAPHIC(8) DEFAULT '', 
		"ERNAM" VARGRAPHIC(12) DEFAULT '', 
		"SPERR" VARGRAPHIC(1) DEFAULT '', 
		"LOEVM" VARGRAPHIC(1) DEFAULT '', 
		"ZUAWA" VARGRAPHIC(3) DEFAULT '', 
		"BUSAB" VARGRAPHIC(2) DEFAULT '', 
		"AKONT" VARGRAPHIC(10) DEFAULT '', 
		"BEGRU" VARGRAPHIC(4) DEFAULT '', 
		"KNRZE" VARGRAPHIC(10) DEFAULT '', 
		"KNRZB" VARGRAPHIC(10) DEFAULT '', 
		"ZAMIM" VARGRAPHIC(1) DEFAULT '', 
		"ZAMIV" VARGRAPHIC(1) DEFAULT '', 
		"ZAMIR" VARGRAPHIC(1) DEFAULT '', 
		"ZAMIB" VARGRAPHIC(1) DEFAULT '', 
		"ZAMIO" VARGRAPHIC(1) DEFAULT '', 
		"ZWELS" VARGRAPHIC(10) DEFAULT '', 
		"XVERR" VARGRAPHIC(1) DEFAULT '', 
		"ZAHLS" VARGRAPHIC(1) DEFAULT '', 
		"ZTERM" VARGRAPHIC(4) DEFAULT '', 
		"WAKON" VARGRAPHIC(4) DEFAULT '', 
		"VZSKZ" VARGRAPHIC(2) DEFAULT '', 
		"ZINDT" VARGRAPHIC(8) DEFAULT '', 
		"ZINRT" VARGRAPHIC(2) DEFAULT '', 
		"EIKTO" VARGRAPHIC(12) DEFAULT '', 
		"ZSABE" VARGRAPHIC(15) DEFAULT '', 
		"KVERM" VARGRAPHIC(30) DEFAULT '', 
		"FDGRV" VARGRAPHIC(10) DEFAULT '', 
		"VRBKZ" VARGRAPHIC(2) DEFAULT '', 
		"VLIBB" VARGRAPHIC(15) DEFAULT '', 
		"VRSZL" VARGRAPHIC(5) DEFAULT '', 
		"VRSPR" VARGRAPHIC(5) DEFAULT '', 
		"VRSNR" VARGRAPHIC(10) DEFAULT '', 
		"VERDT" VARGRAPHIC(8) DEFAULT '', 
		"PERKZ" VARGRAPHIC(1) DEFAULT '', 
		"XDEZV" VARGRAPHIC(1) DEFAULT '', 
		"XAUSZ" VARGRAPHIC(1) DEFAULT '', 
		"WEBTR" VARGRAPHIC(15) DEFAULT '', 
		"REMIT" VARGRAPHIC(10) DEFAULT '', 
		"DATLZ" VARGRAPHIC(8) DEFAULT '', 
		"XZVER" VARGRAPHIC(1) DEFAULT '', 
		"TOGRU" VARGRAPHIC(4) DEFAULT '', 
		"KULTG" VARGRAPHIC(5) DEFAULT '', 
		"HBKID" VARGRAPHIC(5) DEFAULT '', 
		"XPORE" VARGRAPHIC(1) DEFAULT '', 
		"BLNKZ" VARGRAPHIC(2) DEFAULT '', 
		"ALTKN" VARGRAPHIC(10) DEFAULT '', 
		"ZGRUP" VARGRAPHIC(2) DEFAULT '', 
		"URLID" VARGRAPHIC(4) DEFAULT '', 
		"MGRUP" VARGRAPHIC(2) DEFAULT '', 
		"LOCKB" VARGRAPHIC(7) DEFAULT '', 
		"UZAWE" VARGRAPHIC(2) DEFAULT '', 
		"EKVBD" VARGRAPHIC(10) DEFAULT '', 
		"SREGL" VARGRAPHIC(3) DEFAULT '', 
		"XEDIP" VARGRAPHIC(1) DEFAULT '', 
		"FRGRP" VARGRAPHIC(4) DEFAULT '', 
		"VRSDG" VARGRAPHIC(3) DEFAULT '', 
		"TLFXS" VARGRAPHIC(31) DEFAULT '', 
		"INTAD" VARGRAPHIC(130) DEFAULT '', 
		"XKNZB" VARGRAPHIC(1) DEFAULT '', 
		"GUZTE" VARGRAPHIC(4) DEFAULT '', 
		"GRICD" VARGRAPHIC(2) DEFAULT '', 
		"GRIDT" VARGRAPHIC(2) DEFAULT '', 
		"WBRSL" VARGRAPHIC(2) DEFAULT '', 
		"CONFS" VARGRAPHIC(1) DEFAULT '', 
		"UPDAT" VARGRAPHIC(8) DEFAULT '', 
		"UPTIM" VARGRAPHIC(6) DEFAULT '', 
		"NODEL" VARGRAPHIC(1) DEFAULT '', 
		"TLFNS" VARGRAPHIC(30) DEFAULT '', 
		"CESSION_KZ" VARGRAPHIC(2) DEFAULT '', 
		"GMVKZD" VARGRAPHIC(1) DEFAULT '', 
		"CW_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"CW_LEGACY_UK" VARGRAPHIC(120) NOT NULL, 
		"CW_LOB" VARGRAPHIC(10) NOT NULL, 
		"CW_RLOUT" VARGRAPHIC(30) NOT NULL, 
		"CW_CATEGORY" VARGRAPHIC(30) NOT NULL, 
		"CW_VERSION" INTEGER NOT NULL, 
		"CW_LOAD_ID" INTEGER NOT NULL, 
		"PK_KNB1" VARGRAPHIC(250) NOT NULL, 
		"FK_KNA1_EKVBD" VARGRAPHIC(250), 
		"FK_KNA1_KNRZB" VARGRAPHIC(250), 
		"FK_KNA1_KNRZE" VARGRAPHIC(250), 
		"FK_KNA1_KUNNR" VARGRAPHIC(250), 
		"FK_KNA1_REMIT" VARGRAPHIC(250)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."KNVP" (
		"MANDT" VARGRAPHIC(3) DEFAULT '', 
		"KUNNR" VARGRAPHIC(10) DEFAULT '', 
		"VKORG" VARGRAPHIC(4) DEFAULT '', 
		"VTWEG" VARGRAPHIC(2) DEFAULT '', 
		"SPART" VARGRAPHIC(2) DEFAULT '', 
		"PARVW" VARGRAPHIC(2) DEFAULT '', 
		"PARZA" VARGRAPHIC(3) DEFAULT '', 
		"KUNN2" VARGRAPHIC(10) DEFAULT '', 
		"LIFNR" VARGRAPHIC(10) DEFAULT '', 
		"PERNR" VARGRAPHIC(8) DEFAULT '', 
		"PARNR" VARGRAPHIC(10) DEFAULT '', 
		"KNREF" VARGRAPHIC(30) DEFAULT '', 
		"DEFPA" VARGRAPHIC(1) DEFAULT '', 
		"CW_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"CW_LEGACY_UK" VARGRAPHIC(120) NOT NULL, 
		"CW_LOB" VARGRAPHIC(10) NOT NULL, 
		"CW_RLOUT" VARGRAPHIC(30) NOT NULL, 
		"CW_CATEGORY" VARGRAPHIC(30) NOT NULL, 
		"CW_VERSION" INTEGER NOT NULL, 
		"CW_LOAD_ID" INTEGER NOT NULL, 
		"PK_KNVP" VARGRAPHIC(250) NOT NULL, 
		"FK_KNA1_KUNN2" VARGRAPHIC(250), 
		"FK_KNA1_KUNNR" VARGRAPHIC(250)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."KNVV" (
		"MANDT" VARGRAPHIC(3) DEFAULT '', 
		"KUNNR" VARGRAPHIC(10) DEFAULT '', 
		"VKORG" VARGRAPHIC(4) DEFAULT '', 
		"VTWEG" VARGRAPHIC(2) DEFAULT '', 
		"SPART" VARGRAPHIC(2) DEFAULT '', 
		"ERNAM" VARGRAPHIC(12) DEFAULT '', 
		"ERDAT" VARGRAPHIC(8) DEFAULT '', 
		"BEGRU" VARGRAPHIC(4) DEFAULT '', 
		"LOEVM" VARGRAPHIC(1) DEFAULT '', 
		"VERSG" VARGRAPHIC(1) DEFAULT '', 
		"AUFSD" VARGRAPHIC(2) DEFAULT '', 
		"KALKS" VARGRAPHIC(1) DEFAULT '', 
		"KDGRP" VARGRAPHIC(2) DEFAULT '', 
		"BZIRK" VARGRAPHIC(6) DEFAULT '', 
		"KONDA" VARGRAPHIC(2) DEFAULT '', 
		"PLTYP" VARGRAPHIC(2) DEFAULT '', 
		"AWAHR" VARGRAPHIC(3) DEFAULT '', 
		"INCO1" VARGRAPHIC(3) DEFAULT '', 
		"INCO2" VARGRAPHIC(28) DEFAULT '', 
		"LIFSD" VARGRAPHIC(2) DEFAULT '', 
		"AUTLF" VARGRAPHIC(1) DEFAULT '', 
		"ANTLF" VARGRAPHIC(3) DEFAULT '', 
		"KZTLF" VARGRAPHIC(1) DEFAULT '', 
		"KZAZU" VARGRAPHIC(1) DEFAULT '', 
		"CHSPL" VARGRAPHIC(1) DEFAULT '', 
		"LPRIO" VARGRAPHIC(2) DEFAULT '', 
		"EIKTO" VARGRAPHIC(12) DEFAULT '', 
		"VSBED" VARGRAPHIC(2) DEFAULT '', 
		"FAKSD" VARGRAPHIC(2) DEFAULT '', 
		"MRNKZ" VARGRAPHIC(1) DEFAULT '', 
		"PERFK" VARGRAPHIC(2) DEFAULT '', 
		"PERRL" VARGRAPHIC(2) DEFAULT '', 
		"KVAKZ" VARGRAPHIC(1) DEFAULT '', 
		"KVAWT" VARGRAPHIC(15) DEFAULT '', 
		"WAERS" VARGRAPHIC(5) DEFAULT '', 
		"KLABC" VARGRAPHIC(2) DEFAULT '', 
		"KTGRD" VARGRAPHIC(2) DEFAULT '', 
		"ZTERM" VARGRAPHIC(4) DEFAULT '', 
		"VWERK" VARGRAPHIC(4) DEFAULT '', 
		"VKGRP" VARGRAPHIC(3) DEFAULT '', 
		"VKBUR" VARGRAPHIC(4) DEFAULT '', 
		"VSORT" VARGRAPHIC(10) DEFAULT '', 
		"KVGR1" VARGRAPHIC(3) DEFAULT '', 
		"KVGR2" VARGRAPHIC(3) DEFAULT '', 
		"KVGR3" VARGRAPHIC(3) DEFAULT '', 
		"KVGR4" VARGRAPHIC(3) DEFAULT '', 
		"KVGR5" VARGRAPHIC(3) DEFAULT '', 
		"BOKRE" VARGRAPHIC(1) DEFAULT '', 
		"BOIDT" VARGRAPHIC(8) DEFAULT '', 
		"KURST" VARGRAPHIC(4) DEFAULT '', 
		"PRFRE" VARGRAPHIC(1) DEFAULT '', 
		"PRAT1" VARGRAPHIC(1) DEFAULT '', 
		"PRAT2" VARGRAPHIC(1) DEFAULT '', 
		"PRAT3" VARGRAPHIC(1) DEFAULT '', 
		"PRAT4" VARGRAPHIC(1) DEFAULT '', 
		"PRAT5" VARGRAPHIC(1) DEFAULT '', 
		"PRAT6" VARGRAPHIC(1) DEFAULT '', 
		"PRAT7" VARGRAPHIC(1) DEFAULT '', 
		"PRAT8" VARGRAPHIC(1) DEFAULT '', 
		"PRAT9" VARGRAPHIC(1) DEFAULT '', 
		"PRATA" VARGRAPHIC(1) DEFAULT '', 
		"KABSS" VARGRAPHIC(4) DEFAULT '', 
		"KKBER" VARGRAPHIC(4) DEFAULT '', 
		"CASSD" VARGRAPHIC(2) DEFAULT '', 
		"RDOFF" VARGRAPHIC(1) DEFAULT '', 
		"AGREL" VARGRAPHIC(1) DEFAULT '', 
		"MEGRU" VARGRAPHIC(4) DEFAULT '', 
		"UEBTO" VARGRAPHIC(5) DEFAULT '', 
		"UNTTO" VARGRAPHIC(5) DEFAULT '', 
		"UEBTK" VARGRAPHIC(1) DEFAULT '', 
		"PVKSM" VARGRAPHIC(2) DEFAULT '', 
		"PODKZ" VARGRAPHIC(1) DEFAULT '', 
		"PODTG" VARGRAPHIC(13) DEFAULT '', 
		"BLIND" VARGRAPHIC(1) DEFAULT '', 
		"CARRIER_NOTIF" VARGRAPHIC(1) DEFAULT '', 
		"ABEV1_EMLGPFAND" VARGRAPHIC(1) DEFAULT '', 
		"ABEV1_EMLGFORTS" VARGRAPHIC(1) DEFAULT '', 
		"CW_LEGACY_ID" VARGRAPHIC(20) NOT NULL, 
		"CW_LEGACY_UK" VARGRAPHIC(120) NOT NULL, 
		"CW_LOB" VARGRAPHIC(10) NOT NULL, 
		"CW_RLOUT" VARGRAPHIC(30) NOT NULL, 
		"CW_CATEGORY" VARGRAPHIC(30) NOT NULL, 
		"CW_VERSION" INTEGER NOT NULL, 
		"CW_LOAD_ID" INTEGER NOT NULL, 
		"PK_KNVV" VARGRAPHIC(250) NOT NULL, 
		"FK_KNA1_KUNNR" VARGRAPHIC(250)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_FMFGT_ALCT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"ALC" VARGRAPHIC(8) NOT NULL, 
		"TXT30" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_FMFGT_POT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"PMT_OFFICE" VARGRAPHIC(5) NOT NULL, 
		"TXT30" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_J_1ADTYPT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"BUKRS" VARGRAPHIC(4) NOT NULL, 
		"J_1ADTYP" VARGRAPHIC(2) NOT NULL, 
		"TEXT30" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_J_1ATODCT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"J_1ATODC" VARGRAPHIC(2) NOT NULL, 
		"TEXT30" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_J_1BATL1T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"LANGU" VARGRAPHIC(1) NOT NULL, 
		"TAXLAW" VARGRAPHIC(3) NOT NULL, 
		"DESCRIP" VARGRAPHIC(60), 
		"LINE1" VARGRAPHIC(72), 
		"LINE2" VARGRAPHIC(72), 
		"LINE3" VARGRAPHIC(72), 
		"LINE4" VARGRAPHIC(72)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_J_1BATL2T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"LANGU" VARGRAPHIC(1) NOT NULL, 
		"TAXLAW" VARGRAPHIC(3) NOT NULL, 
		"DESCRIP" VARGRAPHIC(60), 
		"LINE1" VARGRAPHIC(72), 
		"LINE2" VARGRAPHIC(72), 
		"LINE3" VARGRAPHIC(72), 
		"LINE4" VARGRAPHIC(72)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_J_1BTXSTGT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"LANGU" VARGRAPHIC(1) NOT NULL, 
		"STGRP" VARGRAPHIC(3) NOT NULL, 
		"DESCRIP" VARGRAPHIC(40)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T002T" (
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"SPRSL" VARGRAPHIC(1) NOT NULL, 
		"SPTXT" VARGRAPHIC(16)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T005F" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"LAND1" VARGRAPHIC(3) NOT NULL, 
		"REGIO" VARGRAPHIC(3) NOT NULL, 
		"COUNC" VARGRAPHIC(3) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T005H" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"LAND1" VARGRAPHIC(3) NOT NULL, 
		"REGIO" VARGRAPHIC(3) NOT NULL, 
		"CITYC" VARGRAPHIC(4) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T005T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"LAND1" VARGRAPHIC(3) NOT NULL, 
		"LANDX" VARGRAPHIC(15), 
		"NATIO" VARGRAPHIC(15), 
		"LANDX50" VARGRAPHIC(50), 
		"NATIO50" VARGRAPHIC(50), 
		"PRQ_SPREGT" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T005U" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"LAND1" VARGRAPHIC(3) NOT NULL, 
		"BLAND" VARGRAPHIC(3) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T006A" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"MSEHI" VARGRAPHIC(3) NOT NULL, 
		"MSEH3" VARGRAPHIC(3), 
		"MSEH6" VARGRAPHIC(6), 
		"MSEHT" VARGRAPHIC(10), 
		"MSEHL" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T008T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"ZAHLS" VARGRAPHIC(1) NOT NULL, 
		"TEXTL" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T009T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"PERIV" VARGRAPHIC(2) NOT NULL, 
		"LTEXT" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T014T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KKBER" VARGRAPHIC(4) NOT NULL, 
		"KKBTX" VARGRAPHIC(35)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T016T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"BRSCH" VARGRAPHIC(4) NOT NULL, 
		"BRTXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T035T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"GRUPP" VARGRAPHIC(10) NOT NULL, 
		"TEXTL" VARGRAPHIC(30), 
		"TEXTK" VARGRAPHIC(10)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T042H" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"UZAWE" VARGRAPHIC(2) NOT NULL, 
		"TXT30" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T043GT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"BUKRS" VARGRAPHIC(4) NOT NULL, 
		"TOGRU" VARGRAPHIC(4) NOT NULL, 
		"TXT30" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T047S" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"MGRUP" VARGRAPHIC(2) NOT NULL, 
		"TEXT1" VARGRAPHIC(50)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T048L" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"XAUSZ" VARGRAPHIC(1) NOT NULL, 
		"TEXT1" VARGRAPHIC(50)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T052T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"URLID" VARGRAPHIC(4) NOT NULL, 
		"URLTX" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T053B" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"SREGL" VARGRAPHIC(3) NOT NULL, 
		"TXT20" VARGRAPHIC(25), 
		"TXT40" VARGRAPHIC(40)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T053W" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"VRSDG" VARGRAPHIC(3) NOT NULL, 
		"VRSTX" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T056X" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"VZSKZ" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T077X" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KTOKD" VARGRAPHIC(4) NOT NULL, 
		"TXT30" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T151T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KDGRP" VARGRAPHIC(2) NOT NULL, 
		"KTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T171T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"BZIRK" VARGRAPHIC(6) NOT NULL, 
		"BZTXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T188T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KONDA" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T189T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"PLTYP" VARGRAPHIC(2) NOT NULL, 
		"PTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_T691Q" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KABSS" VARGRAPHIC(4) NOT NULL, 
		"BEZEI" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TBRCT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"BRACO" VARGRAPHIC(10) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TCURT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"WAERS" VARGRAPHIC(5) NOT NULL, 
		"LTEXT" VARGRAPHIC(40), 
		"KTEXT" VARGRAPHIC(15)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TCURW" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KURST" VARGRAPHIC(4) NOT NULL, 
		"CURVW" VARGRAPHIC(40)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TFACT" (
		"IDENT" VARGRAPHIC(2) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"LTEXT" VARGRAPHIC(60)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TINCT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"INCO1" VARGRAPHIC(3) NOT NULL, 
		"BEZEI" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TKUKT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KUKLA" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TNLST" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"NIELS" VARGRAPHIC(2) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TPART" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"PARVW" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TPRIT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"LPRIO" VARGRAPHIC(2) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TPVDT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"PVKSM" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TSPAT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"SPART" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVFST" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"FAKSP" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVGFT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"GFORM" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVK0T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KATR10" VARGRAPHIC(3) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVK1T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KATR1" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVK2T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KATR2" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVK3T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KATR3" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVK4T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KATR4" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVK5T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KATR5" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVK6T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KATR6" VARGRAPHIC(3) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVK7T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KATR7" VARGRAPHIC(3) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVK8T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KATR8" VARGRAPHIC(3) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVK9T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KATR9" VARGRAPHIC(3) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVKBT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"VKBUR" VARGRAPHIC(4) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVKDT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KALKS" VARGRAPHIC(1) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVKGGT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KDKGR" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVKOT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"VKORG" VARGRAPHIC(4) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVKTT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KTGRD" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVLST" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"LIFSP" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVLVT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"ABRVW" VARGRAPHIC(3) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVSBT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"VSBED" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVSDT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"STGKU" VARGRAPHIC(1) NOT NULL, 
		"BEZEI20" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVTWT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"VTWEG" VARGRAPHIC(2) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVV1T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KVGR1" VARGRAPHIC(3) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVV2T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KVGR2" VARGRAPHIC(3) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVV3T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KVGR3" VARGRAPHIC(3) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVV4T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KVGR4" VARGRAPHIC(3) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TVV5T" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KVGR5" VARGRAPHIC(3) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TWEKT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"KUNGR" VARGRAPHIC(10) NOT NULL, 
		"BEZEI" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TZGRT" (
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"ZGRUP" VARGRAPHIC(2) NOT NULL, 
		"TTEXT" VARGRAPHIC(30)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TZONT" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"LAND1" VARGRAPHIC(3) NOT NULL, 
		"ZONE1" VARGRAPHIC(10) NOT NULL, 
		"VTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_TZUNT" (
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"ZUAWA" VARGRAPHIC(3) NOT NULL, 
		"TTEXT" VARGRAPHIC(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

CREATE TABLE "PLD"."TX_VBWF07" (
		"MANDT" VARGRAPHIC(3) NOT NULL, 
		"SPRAS" VARGRAPHIC(1) NOT NULL, 
		"FRGRP" VARGRAPHIC(4) NOT NULL, 
		"FRGRT" VARGRAPHIC(25)
	)
	DATA CAPTURE NONE 
	COMPRESS NO!

ALTER TABLE "PLD"."CT_AVSO_R_DPOINT" ADD CONSTRAINT "CT_AVSO_R_DPOINT_PK" PRIMARY KEY
	("MANDT", 
	 "AVSO_R_DPOINT")!

ALTER TABLE "PLD"."CT_BUSTYPE" ADD CONSTRAINT "CT_BUSTYPE_PK" PRIMARY KEY
	("MANDT", 
	 "GESTYP")!

ALTER TABLE "PLD"."CT_FMFGT_ALC" ADD CONSTRAINT "CT_FMFGT_ALC_PK" PRIMARY KEY
	("MANDT", 
	 "ALC")!

ALTER TABLE "PLD"."CT_FMFGT_PO" ADD CONSTRAINT "CT_FMFGT_PO_PK" PRIMARY KEY
	("MANDT", 
	 "PMT_OFFICE")!

ALTER TABLE "PLD"."CT_INDUSTYPE" ADD CONSTRAINT "CT_INDUSTYPE_PK" PRIMARY KEY
	("MANDT", 
	 "INDTYPE")!

ALTER TABLE "PLD"."CT_J_1ADTYP" ADD CONSTRAINT "CT_J_1ADTYP_PK" PRIMARY KEY
	("MANDT", 
	 "BUKRS", 
	 "J_1ADTYP")!

ALTER TABLE "PLD"."CT_J_1ATODC" ADD CONSTRAINT "CT_J_1ATODC_PK" PRIMARY KEY
	("MANDT", 
	 "J_1ATODC")!

ALTER TABLE "PLD"."CT_J_1BATL1" ADD CONSTRAINT "CT_J_1BATL1_PK" PRIMARY KEY
	("MANDT", 
	 "TAXLAW")!

ALTER TABLE "PLD"."CT_J_1BATL2" ADD CONSTRAINT "CT_J_1BATL2_PK" PRIMARY KEY
	("MANDT", 
	 "TAXLAW")!

ALTER TABLE "PLD"."CT_J_1BTXSTG" ADD CONSTRAINT "CT_J_1BTXSTG_PK" PRIMARY KEY
	("MANDT", 
	 "STGRP")!

ALTER TABLE "PLD"."CT_MARA" ADD CONSTRAINT "CT_MARA_PK" PRIMARY KEY
	("MANDT", 
	 "MATNR")!

ALTER TABLE "PLD"."CT_T000" ADD CONSTRAINT "CT_T000_PK" PRIMARY KEY
	("MANDT")!

ALTER TABLE "PLD"."CT_T001" ADD CONSTRAINT "CT_T001_PK" PRIMARY KEY
	("MANDT", 
	 "BUKRS")!

ALTER TABLE "PLD"."CT_T001S" ADD CONSTRAINT "CT_T001S_PK" PRIMARY KEY
	("MANDT", 
	 "BUKRS", 
	 "BUSAB")!

ALTER TABLE "PLD"."CT_T001W" ADD CONSTRAINT "CT_T001W_PK" PRIMARY KEY
	("MANDT", 
	 "WERKS")!

ALTER TABLE "PLD"."CT_T002" ADD CONSTRAINT "CT_T002_PK" PRIMARY KEY
	("SPRAS")!

ALTER TABLE "PLD"."CT_T005" ADD CONSTRAINT "CT_T005_PK" PRIMARY KEY
	("MANDT", 
	 "LAND1")!

ALTER TABLE "PLD"."CT_T005E" ADD CONSTRAINT "CT_T005E_PK" PRIMARY KEY
	("MANDT", 
	 "LAND1", 
	 "REGIO", 
	 "COUNC")!

ALTER TABLE "PLD"."CT_T005G" ADD CONSTRAINT "CT_T005G_PK" PRIMARY KEY
	("MANDT", 
	 "LAND1", 
	 "REGIO", 
	 "CITYC")!

ALTER TABLE "PLD"."CT_T005S" ADD CONSTRAINT "CT_T005S_PK" PRIMARY KEY
	("MANDT", 
	 "LAND1", 
	 "BLAND")!

ALTER TABLE "PLD"."CT_T006" ADD CONSTRAINT "CT_T006_PK" PRIMARY KEY
	("MANDT", 
	 "MSEHI")!

ALTER TABLE "PLD"."CT_T008" ADD CONSTRAINT "CT_T008_PK" PRIMARY KEY
	("MANDT", 
	 "ZAHLS")!

ALTER TABLE "PLD"."CT_T009" ADD CONSTRAINT "CT_T009_PK" PRIMARY KEY
	("MANDT", 
	 "PERIV")!

ALTER TABLE "PLD"."CT_T014" ADD CONSTRAINT "CT_T014_PK" PRIMARY KEY
	("MANDT", 
	 "KKBER")!

ALTER TABLE "PLD"."CT_T016" ADD CONSTRAINT "CT_T016_PK" PRIMARY KEY
	("MANDT", 
	 "BRSCH")!

ALTER TABLE "PLD"."CT_T035" ADD CONSTRAINT "CT_T035_PK" PRIMARY KEY
	("MANDT", 
	 "GRUPP")!

ALTER TABLE "PLD"."CT_T042F" ADD CONSTRAINT "CT_T042F_PK" PRIMARY KEY
	("MANDT", 
	 "UZAWE")!

ALTER TABLE "PLD"."CT_T043G" ADD CONSTRAINT "CT_T043G_PK" PRIMARY KEY
	("MANDT", 
	 "BUKRS", 
	 "TOGRU")!

ALTER TABLE "PLD"."CT_T047R" ADD CONSTRAINT "CT_T047R_PK" PRIMARY KEY
	("MANDT", 
	 "MGRUP")!

ALTER TABLE "PLD"."CT_T048K" ADD CONSTRAINT "CT_T048K_PK" PRIMARY KEY
	("MANDT", 
	 "XAUSZ")!

ALTER TABLE "PLD"."CT_T049L" ADD CONSTRAINT "CT_T049L_PK" PRIMARY KEY
	("MANDT", 
	 "BUKRS", 
	 "LOCKB")!

ALTER TABLE "PLD"."CT_T052A" ADD CONSTRAINT "CT_T052A_PK" PRIMARY KEY
	("MANDT", 
	 "URLID")!

ALTER TABLE "PLD"."CT_T053A" ADD CONSTRAINT "CT_T053A_PK" PRIMARY KEY
	("MANDT", 
	 "SREGL")!

ALTER TABLE "PLD"."CT_T053V" ADD CONSTRAINT "CT_T053V_PK" PRIMARY KEY
	("MANDT", 
	 "VRSDG")!

ALTER TABLE "PLD"."CT_T056" ADD CONSTRAINT "CT_T056_PK" PRIMARY KEY
	("MANDT", 
	 "VZSKZ")!

ALTER TABLE "PLD"."CT_T077D" ADD CONSTRAINT "CT_T077D_PK" PRIMARY KEY
	("MANDT", 
	 "KTOKD")!

ALTER TABLE "PLD"."CT_T151" ADD CONSTRAINT "CT_T151_PK" PRIMARY KEY
	("MANDT", 
	 "KDGRP")!

ALTER TABLE "PLD"."CT_T171" ADD CONSTRAINT "CT_T171_PK" PRIMARY KEY
	("MANDT", 
	 "BZIRK")!

ALTER TABLE "PLD"."CT_T188" ADD CONSTRAINT "CT_T188_PK" PRIMARY KEY
	("MANDT", 
	 "KONDA")!

ALTER TABLE "PLD"."CT_T189" ADD CONSTRAINT "CT_T189_PK" PRIMARY KEY
	("MANDT", 
	 "PLTYP")!

ALTER TABLE "PLD"."CT_T691P" ADD CONSTRAINT "CT_T691P_PK" PRIMARY KEY
	("MANDT", 
	 "KABSS")!

ALTER TABLE "PLD"."CT_T880" ADD CONSTRAINT "CT_T880_PK" PRIMARY KEY
	("MANDT", 
	 "RCOMP")!

ALTER TABLE "PLD"."CT_TBRC" ADD CONSTRAINT "CT_TBRC_PK" PRIMARY KEY
	("MANDT", 
	 "BRACO")!

ALTER TABLE "PLD"."CT_TCURC" ADD CONSTRAINT "CT_TCURC_PK" PRIMARY KEY
	("MANDT", 
	 "WAERS")!

ALTER TABLE "PLD"."CT_TCURV" ADD CONSTRAINT "CT_TCURV_PK" PRIMARY KEY
	("MANDT", 
	 "KURST")!

ALTER TABLE "PLD"."CT_TFACD" ADD CONSTRAINT "CT_TFACD_PK" PRIMARY KEY
	("IDENT")!

ALTER TABLE "PLD"."CT_TINC" ADD CONSTRAINT "CT_TINC_PK" PRIMARY KEY
	("MANDT", 
	 "INCO1")!

ALTER TABLE "PLD"."CT_TKUKL" ADD CONSTRAINT "CT_TKUKL_PK" PRIMARY KEY
	("MANDT", 
	 "KUKLA")!

ALTER TABLE "PLD"."CT_TNLS" ADD CONSTRAINT "CT_TNLS_PK" PRIMARY KEY
	("MANDT", 
	 "NIELS")!

ALTER TABLE "PLD"."CT_TPAR" ADD CONSTRAINT "CT_TPAR_PK" PRIMARY KEY
	("MANDT", 
	 "PARVW")!

ALTER TABLE "PLD"."CT_TPRIO" ADD CONSTRAINT "CT_TPRIO_PK" PRIMARY KEY
	("MANDT", 
	 "LPRIO")!

ALTER TABLE "PLD"."CT_TPVD" ADD CONSTRAINT "CT_TPVD_PK" PRIMARY KEY
	("MANDT", 
	 "PVKSM")!

ALTER TABLE "PLD"."CT_TSPA" ADD CONSTRAINT "CT_TSPA_PK" PRIMARY KEY
	("MANDT", 
	 "SPART")!

ALTER TABLE "PLD"."CT_TVAST" ADD CONSTRAINT "CT_TVAST_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "AUFSP")!

ALTER TABLE "PLD"."CT_TVBUR" ADD CONSTRAINT "CT_TVBUR_PK" PRIMARY KEY
	("MANDT", 
	 "VKBUR")!

ALTER TABLE "PLD"."CT_TVBVK" ADD CONSTRAINT "CT_TVBVK_PK" PRIMARY KEY
	("MANDT", 
	 "VKBUR", 
	 "VKGRP")!

ALTER TABLE "PLD"."CT_TVFS" ADD CONSTRAINT "CT_TVFS_PK" PRIMARY KEY
	("MANDT", 
	 "FAKSP")!

ALTER TABLE "PLD"."CT_TVGF" ADD CONSTRAINT "CT_TVGF_PK" PRIMARY KEY
	("MANDT", 
	 "GFORM")!

ALTER TABLE "PLD"."CT_TVK0" ADD CONSTRAINT "CT_TVK0_PK" PRIMARY KEY
	("MANDT", 
	 "KATR10")!

ALTER TABLE "PLD"."CT_TVK1" ADD CONSTRAINT "CT_TVK1_PK" PRIMARY KEY
	("MANDT", 
	 "KATR1")!

ALTER TABLE "PLD"."CT_TVK2" ADD CONSTRAINT "CT_TVK2_PK" PRIMARY KEY
	("MANDT", 
	 "KATR2")!

ALTER TABLE "PLD"."CT_TVK3" ADD CONSTRAINT "CT_TVK3_PK" PRIMARY KEY
	("MANDT", 
	 "KATR3")!

ALTER TABLE "PLD"."CT_TVK4" ADD CONSTRAINT "CT_TVK4_PK" PRIMARY KEY
	("MANDT", 
	 "KATR4")!

ALTER TABLE "PLD"."CT_TVK5" ADD CONSTRAINT "CT_TVK5_PK" PRIMARY KEY
	("MANDT", 
	 "KATR5")!

ALTER TABLE "PLD"."CT_TVK6" ADD CONSTRAINT "CT_TVK6_PK" PRIMARY KEY
	("MANDT", 
	 "KATR6")!

ALTER TABLE "PLD"."CT_TVK7" ADD CONSTRAINT "CT_TVK7_PK" PRIMARY KEY
	("MANDT", 
	 "KATR7")!

ALTER TABLE "PLD"."CT_TVK8" ADD CONSTRAINT "CT_TVK8_PK" PRIMARY KEY
	("MANDT", 
	 "KATR8")!

ALTER TABLE "PLD"."CT_TVK9" ADD CONSTRAINT "CT_TVK9_PK" PRIMARY KEY
	("MANDT", 
	 "KATR9")!

ALTER TABLE "PLD"."CT_TVKD" ADD CONSTRAINT "CT_TVKD_PK" PRIMARY KEY
	("MANDT", 
	 "KALKS")!

ALTER TABLE "PLD"."CT_TVKGG" ADD CONSTRAINT "CT_TVKGG_PK" PRIMARY KEY
	("MANDT", 
	 "KDKGR")!

ALTER TABLE "PLD"."CT_TVKO" ADD CONSTRAINT "CT_TVKO_PK" PRIMARY KEY
	("MANDT", 
	 "VKORG")!

ALTER TABLE "PLD"."CT_TVKT" ADD CONSTRAINT "CT_TVKT_PK" PRIMARY KEY
	("MANDT", 
	 "KTGRD")!

ALTER TABLE "PLD"."CT_TVLS" ADD CONSTRAINT "CT_TVLS_PK" PRIMARY KEY
	("MANDT", 
	 "LIFSP")!

ALTER TABLE "PLD"."CT_TVLV" ADD CONSTRAINT "CT_TVLV_PK" PRIMARY KEY
	("MANDT", 
	 "ABRVW")!

ALTER TABLE "PLD"."CT_TVSB" ADD CONSTRAINT "CT_TVSB_PK" PRIMARY KEY
	("MANDT", 
	 "VSBED")!

ALTER TABLE "PLD"."CT_TVSD" ADD CONSTRAINT "CT_TVSD_PK" PRIMARY KEY
	("MANDT", 
	 "STGKU")!

ALTER TABLE "PLD"."CT_TVTW" ADD CONSTRAINT "CT_TVTW_PK" PRIMARY KEY
	("MANDT", 
	 "VTWEG")!

ALTER TABLE "PLD"."CT_TVV1" ADD CONSTRAINT "CT_TVV1_PK" PRIMARY KEY
	("MANDT", 
	 "KVGR1")!

ALTER TABLE "PLD"."CT_TVV2" ADD CONSTRAINT "CT_TVV2_PK" PRIMARY KEY
	("MANDT", 
	 "KVGR2")!

ALTER TABLE "PLD"."CT_TVV3" ADD CONSTRAINT "CT_TVV3_PK" PRIMARY KEY
	("MANDT", 
	 "KVGR3")!

ALTER TABLE "PLD"."CT_TVV4" ADD CONSTRAINT "CT_TVV4_PK" PRIMARY KEY
	("MANDT", 
	 "KVGR4")!

ALTER TABLE "PLD"."CT_TVV5" ADD CONSTRAINT "CT_TVV5_PK" PRIMARY KEY
	("MANDT", 
	 "KVGR5")!

ALTER TABLE "PLD"."CT_TWEK" ADD CONSTRAINT "CT_TWEK_PK" PRIMARY KEY
	("MANDT", 
	 "KUNGR")!

ALTER TABLE "PLD"."CT_TZGR" ADD CONSTRAINT "CT_TZGR_PK" PRIMARY KEY
	("ZGRUP")!

ALTER TABLE "PLD"."CT_TZONE" ADD CONSTRAINT "CT_TZONE_PK" PRIMARY KEY
	("MANDT", 
	 "LAND1", 
	 "ZONE1")!

ALTER TABLE "PLD"."CT_TZUN" ADD CONSTRAINT "CT_TZUN_PK" PRIMARY KEY
	("ZUAWA")!

ALTER TABLE "PLD"."CT_VBUK" ADD CONSTRAINT "CT_VBUK_PK" PRIMARY KEY
	("MANDT", 
	 "VBELN")!

ALTER TABLE "PLD"."CT_VBWF08" ADD CONSTRAINT "CT_VBWF08_PK" PRIMARY KEY
	("MANDT", 
	 "FRGRP")!

ALTER TABLE "PLD"."DT_AWAHR" ADD CONSTRAINT "DT_AWAHR_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_DEAR3" ADD CONSTRAINT "DT_DEAR3_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_DTAMS" ADD CONSTRAINT "DT_DTAMS_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_DUEFL_BKPF" ADD CONSTRAINT "DT_DUEFL_BKPF_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_J_1BINDUS1" ADD CONSTRAINT "DT_J_1BINDUS1_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_KZTLF" ADD CONSTRAINT "DT_KZTLF_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_PRATK" ADD CONSTRAINT "DT_PRATK_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_QKZ" ADD CONSTRAINT "DT_QKZ_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_STKZA" ADD CONSTRAINT "DT_STKZA_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_STKZN" ADD CONSTRAINT "DT_STKZN_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_XFELD" ADD CONSTRAINT "DT_XFELD_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT_ZINRT" ADD CONSTRAINT "DT_ZINRT_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT__BEV1_EMGFORTS" ADD CONSTRAINT "DT__BEV1_EMGFORTS_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT__BEV1_EMGPFAND" ADD CONSTRAINT "DT__BEV1_EMGPFAND_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT__VSO_M_LOAD_PREF" ADD CONSTRAINT "DT__VSO_M_LOAD_PREF_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT__VSO_M_SIDE_PREF" ADD CONSTRAINT "DT__VSO_M_SIDE_PREF_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."DT__VSO_M_XFIELD" ADD CONSTRAINT "DT__VSO_M_XFIELD_PK" PRIMARY KEY
	("VALPOS")!

ALTER TABLE "PLD"."KNA1" ADD CONSTRAINT "KNA1_PK" PRIMARY KEY
	("PK_KNA1")!

ALTER TABLE "PLD"."KNB1" ADD CONSTRAINT "KNB1_PK" PRIMARY KEY
	("PK_KNB1")!

ALTER TABLE "PLD"."KNVP" ADD CONSTRAINT "KNVP_PK" PRIMARY KEY
	("PK_KNVP")!

ALTER TABLE "PLD"."KNVV" ADD CONSTRAINT "KNVV_PK" PRIMARY KEY
	("PK_KNVV")!

ALTER TABLE "PLD"."TX_FMFGT_ALCT" ADD CONSTRAINT "TX_FMFGT_ALCT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "ALC")!

ALTER TABLE "PLD"."TX_FMFGT_POT" ADD CONSTRAINT "TX_FMFGT_POT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "PMT_OFFICE")!

ALTER TABLE "PLD"."TX_J_1ADTYPT" ADD CONSTRAINT "TX_J_1ADTYPT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "BUKRS", 
	 "J_1ADTYP")!

ALTER TABLE "PLD"."TX_J_1ATODCT" ADD CONSTRAINT "TX_J_1ATODCT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "J_1ATODC")!

ALTER TABLE "PLD"."TX_J_1BATL1T" ADD CONSTRAINT "TX_J_1BATL1T_PK" PRIMARY KEY
	("MANDT", 
	 "LANGU", 
	 "TAXLAW")!

ALTER TABLE "PLD"."TX_J_1BATL2T" ADD CONSTRAINT "TX_J_1BATL2T_PK" PRIMARY KEY
	("MANDT", 
	 "LANGU", 
	 "TAXLAW")!

ALTER TABLE "PLD"."TX_J_1BTXSTGT" ADD CONSTRAINT "TX_J_1BTXSTGT_PK" PRIMARY KEY
	("MANDT", 
	 "LANGU", 
	 "STGRP")!

ALTER TABLE "PLD"."TX_T002T" ADD CONSTRAINT "TX_T002T_PK" PRIMARY KEY
	("SPRAS", 
	 "SPRSL")!

ALTER TABLE "PLD"."TX_T005F" ADD CONSTRAINT "TX_T005F_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "LAND1", 
	 "REGIO", 
	 "COUNC")!

ALTER TABLE "PLD"."TX_T005H" ADD CONSTRAINT "TX_T005H_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "LAND1", 
	 "REGIO", 
	 "CITYC")!

ALTER TABLE "PLD"."TX_T005T" ADD CONSTRAINT "TX_T005T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "LAND1")!

ALTER TABLE "PLD"."TX_T005U" ADD CONSTRAINT "TX_T005U_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "LAND1", 
	 "BLAND")!

ALTER TABLE "PLD"."TX_T006A" ADD CONSTRAINT "TX_T006A_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "MSEHI")!

ALTER TABLE "PLD"."TX_T008T" ADD CONSTRAINT "TX_T008T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "ZAHLS")!

ALTER TABLE "PLD"."TX_T009T" ADD CONSTRAINT "TX_T009T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "PERIV")!

ALTER TABLE "PLD"."TX_T014T" ADD CONSTRAINT "TX_T014T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KKBER")!

ALTER TABLE "PLD"."TX_T016T" ADD CONSTRAINT "TX_T016T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "BRSCH")!

ALTER TABLE "PLD"."TX_T035T" ADD CONSTRAINT "TX_T035T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "GRUPP")!

ALTER TABLE "PLD"."TX_T042H" ADD CONSTRAINT "TX_T042H_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "UZAWE")!

ALTER TABLE "PLD"."TX_T043GT" ADD CONSTRAINT "TX_T043GT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "BUKRS", 
	 "TOGRU")!

ALTER TABLE "PLD"."TX_T047S" ADD CONSTRAINT "TX_T047S_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "MGRUP")!

ALTER TABLE "PLD"."TX_T048L" ADD CONSTRAINT "TX_T048L_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "XAUSZ")!

ALTER TABLE "PLD"."TX_T052T" ADD CONSTRAINT "TX_T052T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "URLID")!

ALTER TABLE "PLD"."TX_T053B" ADD CONSTRAINT "TX_T053B_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "SREGL")!

ALTER TABLE "PLD"."TX_T053W" ADD CONSTRAINT "TX_T053W_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "VRSDG")!

ALTER TABLE "PLD"."TX_T056X" ADD CONSTRAINT "TX_T056X_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "VZSKZ")!

ALTER TABLE "PLD"."TX_T077X" ADD CONSTRAINT "TX_T077X_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KTOKD")!

ALTER TABLE "PLD"."TX_T151T" ADD CONSTRAINT "TX_T151T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KDGRP")!

ALTER TABLE "PLD"."TX_T171T" ADD CONSTRAINT "TX_T171T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "BZIRK")!

ALTER TABLE "PLD"."TX_T188T" ADD CONSTRAINT "TX_T188T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KONDA")!

ALTER TABLE "PLD"."TX_T189T" ADD CONSTRAINT "TX_T189T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "PLTYP")!

ALTER TABLE "PLD"."TX_T691Q" ADD CONSTRAINT "TX_T691Q_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KABSS")!

ALTER TABLE "PLD"."TX_TBRCT" ADD CONSTRAINT "TX_TBRCT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "BRACO")!

ALTER TABLE "PLD"."TX_TCURT" ADD CONSTRAINT "TX_TCURT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "WAERS")!

ALTER TABLE "PLD"."TX_TCURW" ADD CONSTRAINT "TX_TCURW_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KURST")!

ALTER TABLE "PLD"."TX_TFACT" ADD CONSTRAINT "TX_TFACT_PK" PRIMARY KEY
	("IDENT", 
	 "SPRAS")!

ALTER TABLE "PLD"."TX_TINCT" ADD CONSTRAINT "TX_TINCT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "INCO1")!

ALTER TABLE "PLD"."TX_TKUKT" ADD CONSTRAINT "TX_TKUKT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KUKLA")!

ALTER TABLE "PLD"."TX_TNLST" ADD CONSTRAINT "TX_TNLST_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "NIELS")!

ALTER TABLE "PLD"."TX_TPART" ADD CONSTRAINT "TX_TPART_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "PARVW")!

ALTER TABLE "PLD"."TX_TPRIT" ADD CONSTRAINT "TX_TPRIT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "LPRIO")!

ALTER TABLE "PLD"."TX_TPVDT" ADD CONSTRAINT "TX_TPVDT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "PVKSM")!

ALTER TABLE "PLD"."TX_TSPAT" ADD CONSTRAINT "TX_TSPAT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "SPART")!

ALTER TABLE "PLD"."TX_TVFST" ADD CONSTRAINT "TX_TVFST_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "FAKSP")!

ALTER TABLE "PLD"."TX_TVGFT" ADD CONSTRAINT "TX_TVGFT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "GFORM")!

ALTER TABLE "PLD"."TX_TVK0T" ADD CONSTRAINT "TX_TVK0T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KATR10")!

ALTER TABLE "PLD"."TX_TVK1T" ADD CONSTRAINT "TX_TVK1T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KATR1")!

ALTER TABLE "PLD"."TX_TVK2T" ADD CONSTRAINT "TX_TVK2T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KATR2")!

ALTER TABLE "PLD"."TX_TVK3T" ADD CONSTRAINT "TX_TVK3T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KATR3")!

ALTER TABLE "PLD"."TX_TVK4T" ADD CONSTRAINT "TX_TVK4T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KATR4")!

ALTER TABLE "PLD"."TX_TVK5T" ADD CONSTRAINT "TX_TVK5T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KATR5")!

ALTER TABLE "PLD"."TX_TVK6T" ADD CONSTRAINT "TX_TVK6T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KATR6")!

ALTER TABLE "PLD"."TX_TVK7T" ADD CONSTRAINT "TX_TVK7T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KATR7")!

ALTER TABLE "PLD"."TX_TVK8T" ADD CONSTRAINT "TX_TVK8T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KATR8")!

ALTER TABLE "PLD"."TX_TVK9T" ADD CONSTRAINT "TX_TVK9T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KATR9")!

ALTER TABLE "PLD"."TX_TVKBT" ADD CONSTRAINT "TX_TVKBT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "VKBUR")!

ALTER TABLE "PLD"."TX_TVKDT" ADD CONSTRAINT "TX_TVKDT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KALKS")!

ALTER TABLE "PLD"."TX_TVKGGT" ADD CONSTRAINT "TX_TVKGGT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KDKGR")!

ALTER TABLE "PLD"."TX_TVKOT" ADD CONSTRAINT "TX_TVKOT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "VKORG")!

ALTER TABLE "PLD"."TX_TVKTT" ADD CONSTRAINT "TX_TVKTT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KTGRD")!

ALTER TABLE "PLD"."TX_TVLST" ADD CONSTRAINT "TX_TVLST_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "LIFSP")!

ALTER TABLE "PLD"."TX_TVLVT" ADD CONSTRAINT "TX_TVLVT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "ABRVW")!

ALTER TABLE "PLD"."TX_TVSBT" ADD CONSTRAINT "TX_TVSBT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "VSBED")!

ALTER TABLE "PLD"."TX_TVSDT" ADD CONSTRAINT "TX_TVSDT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "STGKU")!

ALTER TABLE "PLD"."TX_TVTWT" ADD CONSTRAINT "TX_TVTWT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "VTWEG")!

ALTER TABLE "PLD"."TX_TVV1T" ADD CONSTRAINT "TX_TVV1T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KVGR1")!

ALTER TABLE "PLD"."TX_TVV2T" ADD CONSTRAINT "TX_TVV2T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KVGR2")!

ALTER TABLE "PLD"."TX_TVV3T" ADD CONSTRAINT "TX_TVV3T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KVGR3")!

ALTER TABLE "PLD"."TX_TVV4T" ADD CONSTRAINT "TX_TVV4T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KVGR4")!

ALTER TABLE "PLD"."TX_TVV5T" ADD CONSTRAINT "TX_TVV5T_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KVGR5")!

ALTER TABLE "PLD"."TX_TWEKT" ADD CONSTRAINT "TX_TWEKT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "KUNGR")!

ALTER TABLE "PLD"."TX_TZGRT" ADD CONSTRAINT "TX_TZGRT_PK" PRIMARY KEY
	("SPRAS", 
	 "ZGRUP")!

ALTER TABLE "PLD"."TX_TZONT" ADD CONSTRAINT "TX_TZONT_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "LAND1", 
	 "ZONE1")!

ALTER TABLE "PLD"."TX_TZUNT" ADD CONSTRAINT "TX_TZUNT_PK" PRIMARY KEY
	("SPRAS", 
	 "ZUAWA")!

ALTER TABLE "PLD"."TX_VBWF07" ADD CONSTRAINT "TX_VBWF07_PK" PRIMARY KEY
	("MANDT", 
	 "SPRAS", 
	 "FRGRP")!

ALTER TABLE "PLD"."KNA1" ADD CONSTRAINT "KNA1_KNA1_FK" FOREIGN KEY
	("FK_KNA1_FISKN")
	REFERENCES "PLD"."KNA1"
	("PK_KNA1")
	NOT ENFORCED!

ALTER TABLE "PLD"."KNA1" ADD CONSTRAINT "KNA1_KNA1_FK1" FOREIGN KEY
	("FK_KNA1_KNRZA")
	REFERENCES "PLD"."KNA1"
	("PK_KNA1")
	NOT ENFORCED!

ALTER TABLE "PLD"."KNB1" ADD CONSTRAINT "KNB1_KNA1_FK" FOREIGN KEY
	("FK_KNA1_EKVBD")
	REFERENCES "PLD"."KNA1"
	("PK_KNA1")
	NOT ENFORCED!

ALTER TABLE "PLD"."KNB1" ADD CONSTRAINT "KNB1_KNA1_FK1" FOREIGN KEY
	("FK_KNA1_KNRZB")
	REFERENCES "PLD"."KNA1"
	("PK_KNA1")
	NOT ENFORCED!

ALTER TABLE "PLD"."KNB1" ADD CONSTRAINT "KNB1_KNA1_FK2" FOREIGN KEY
	("FK_KNA1_KNRZE")
	REFERENCES "PLD"."KNA1"
	("PK_KNA1")
	NOT ENFORCED!

ALTER TABLE "PLD"."KNB1" ADD CONSTRAINT "KNB1_KNA1_FK3" FOREIGN KEY
	("FK_KNA1_KUNNR")
	REFERENCES "PLD"."KNA1"
	("PK_KNA1")
	NOT ENFORCED!

ALTER TABLE "PLD"."KNB1" ADD CONSTRAINT "KNB1_KNA1_FK4" FOREIGN KEY
	("FK_KNA1_REMIT")
	REFERENCES "PLD"."KNA1"
	("PK_KNA1")
	NOT ENFORCED!

ALTER TABLE "PLD"."KNVP" ADD CONSTRAINT "KNVP_KNA1_FK" FOREIGN KEY
	("FK_KNA1_KUNN2")
	REFERENCES "PLD"."KNA1"
	("PK_KNA1")
	NOT ENFORCED!

ALTER TABLE "PLD"."KNVP" ADD CONSTRAINT "KNVP_KNA1_FK1" FOREIGN KEY
	("FK_KNA1_KUNNR")
	REFERENCES "PLD"."KNA1"
	("PK_KNA1")
	NOT ENFORCED!

ALTER TABLE "PLD"."KNVV" ADD CONSTRAINT "KNVV_KNA1_FK" FOREIGN KEY
	("FK_KNA1_KUNNR")
	REFERENCES "PLD"."KNA1"
	("PK_KNA1")
	NOT ENFORCED!

